/**
 * R-101 — the **capture script source**, embedded as a TS string and written by
 * the scaffold into `context/telemetry/capture.mjs` (like every generated file,
 * no runtime template copy). It is a **zero-dependency ESM** module (Node built-ins
 * only), because it ships into target repos and is run standalone by the VS Code
 * task (R-103); it therefore re-implements the pricing / aggregation / estimator
 * that `model/telemetry.ts` owns on the core side (kept in lock-step by
 * `tests/capture-script.test.ts`, which imports the emitted script).
 *
 * What it does, per run (defensive — it never throws; a failure to locate a
 * transcript degrades to a no-op):
 *  1. Identify the developer (`git config user.email`/`user.name`).
 *  2. Locate this session's transcripts — Claude Code local sessions
 *     (`~/.claude/projects/<cwd-slug>/*.jsonl`) and, best-effort, the VS Code
 *     Copilot chat logs (`…/workspaceStorage/<hash>/chatSessions/*.json`; the
 *     `<hash>` is fragile, so a miss is tolerated).
 *  3. Derive one record per session: skill/agent, a short description (first user
 *     prompt), model, token split, and USD cost from the pricing table.
 *  4. On **Claude** prefer the real per-message `usage` in the transcript
 *     (`source: "real"`, R-102); on **Copilot** estimate from text
 *     (`source: "estimate"`) — the two are never merged.
 *  5. Rebuild each per-user `<slug>.jsonl` (idempotent: one line per session,
 *     keyed by session id) and the aggregate `index.json` the dashboard reads.
 *
 * The pure helpers are exported so they can be unit-tested; `main()` runs only
 * when the file is executed directly.
 */
export const CAPTURE_SCRIPT = String.raw`#!/usr/bin/env node
// context/telemetry/capture.mjs — AI cost & value capture (R-101/R-102).
// Zero-dependency ESM. Generated by the QA-process scaffolder; do not edit by hand.
// Re-run automatically by .vscode/tasks.json. Never throws: a missing transcript
// simply captures nothing.
import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import {
  existsSync, readFileSync, readdirSync, writeFileSync, mkdirSync, statSync,
} from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { createRequire } from "node:module";

// --- pricing (mirror of core/src/model/telemetry.ts:PRICING) ----------------
export const PRICING = {
  "claude-opus-4": { input: 15, output: 75, cacheRead: 1.5, cacheCreation: 18.75 },
  "claude-sonnet-4": { input: 3, output: 15, cacheRead: 0.3, cacheCreation: 3.75 },
  "claude-sonnet-5": { input: 3, output: 15, cacheRead: 0.3, cacheCreation: 3.75 },
  "claude-haiku-4": { input: 1, output: 5, cacheRead: 0.1, cacheCreation: 1.25 },
  "claude-fable-5": { input: 3, output: 15, cacheRead: 0.3, cacheCreation: 3.75 },
  "gpt-4o": { input: 2.5, output: 10, cacheRead: 1.25, cacheCreation: 2.5 },
  "gpt-4.1": { input: 2, output: 8, cacheRead: 0.5, cacheCreation: 2 },
  "gpt-5": { input: 1.25, output: 10, cacheRead: 0.125, cacheCreation: 1.25 },
  "o4-mini": { input: 1.1, output: 4.4, cacheRead: 0.275, cacheCreation: 1.1 },
  default: { input: 3, output: 15, cacheRead: 0.3, cacheCreation: 3.75 },
};

export function priceFor(model) {
  const id = String(model || "").toLowerCase();
  let best = null;
  for (const key of Object.keys(PRICING)) {
    if (key === "default") continue;
    if (id.startsWith(key) && (best === null || key.length > best.length)) best = key;
  }
  return PRICING[best || "default"];
}

export function costUsd(model, tokens) {
  const p = priceFor(model);
  const usd = (tokens.input * p.input + tokens.output * p.output +
    tokens.cacheRead * p.cacheRead + tokens.cacheCreation * p.cacheCreation) / 1000000;
  return Math.round(usd * 1e6) / 1e6;
}

// --- token estimator (tiktoken cl100k if globally importable, else chars/4) --
let _enc; // undefined = not tried, null = unavailable
function encoder() {
  if (_enc !== undefined) return _enc;
  try {
    const require = createRequire(import.meta.url);
    _enc = require("tiktoken").get_encoding("cl100k_base");
  } catch { _enc = null; }
  return _enc;
}
export function estimateTokens(text) {
  if (!text) return 0;
  const enc = encoder();
  if (enc) { try { return enc.encode(text).length; } catch { /* fall through */ } }
  return Math.ceil(String(text).length / 4);
}

// --- identity ----------------------------------------------------------------
export function emailSlug(email) {
  const s = String(email || "").toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return s.length > 0 ? s : "unknown";
}
export function anonymizeEmail(email) {
  return "anon-" + createHash("sha256").update(String(email || "").toLowerCase(), "utf8").digest("hex").slice(0, 12);
}
function gitConfig(root, key) {
  try {
    return execFileSync("git", ["config", "--get", key], { cwd: root, encoding: "utf8" }).trim();
  } catch { return ""; }
}

// --- aggregation (mirror of telemetry.ts:aggregateRecords) -------------------
function tokenTotal(t) { return (t.input || 0) + (t.output || 0) + (t.cacheRead || 0) + (t.cacheCreation || 0); }
function emptySummary() { return { records: 0, costUsd: 0, tokens: 0, real: 0, estimate: 0 }; }
function addTo(s, r) {
  s.records += 1; s.costUsd += r.costUsd || 0; s.tokens += tokenTotal(r.tokens || {});
  if (r.source === "real") s.real += 1; else s.estimate += 1;
}
function round(s) { s.costUsd = Math.round(s.costUsd * 1e6) / 1e6; }
function groupBy(records, keyOf) {
  const map = new Map();
  for (const r of records) {
    const key = keyOf(r);
    if (!key) continue;
    let g = map.get(key);
    if (!g) { g = Object.assign({ key }, emptySummary()); map.set(key, g); }
    addTo(g, r);
    if (r.description) g.description = r.description;
  }
  const out = [...map.values()];
  for (const g of out) round(g);
  out.sort((a, b) => b.costUsd - a.costUsd || a.key.localeCompare(b.key));
  return out;
}
export function aggregateRecords(records) {
  const totals = emptySummary();
  for (const r of records) addTo(totals, r);
  round(totals);
  return {
    schemaVersion: 1, totals,
    bySkill: groupBy(records, (r) => r.skill),
    byUser: groupBy(records, (r) => r.user),
    byPlatform: groupBy(records, (r) => r.platform),
    byWorkId: groupBy(records, (r) => r.workId),
  };
}

// --- Claude transcript → one session record ----------------------------------
function textOf(content) {
  if (typeof content === "string") return content;
  if (Array.isArray(content)) {
    return content.map((b) => {
      if (typeof b === "string") return b;
      if (b && b.type === "text") return b.text || "";
      if (b && b.type === "thinking") return b.thinking || "";
      return "";
    }).join(" ");
  }
  return "";
}
function isRealPrompt(t) {
  // Skip tool results, local-command wrappers, and system-reminder-only messages.
  return t && !/^<(local-command|command-name|command-message)/.test(t.trim()) &&
    !/^\[?\{?"?tool_result/.test(t.trim());
}
function shortDesc(t) {
  return String(t).replace(/<[^>]+>/g, " ").replace(/\s+/g, " ").trim().slice(0, 100);
}
/**
 * One record from a Claude session's JSONL text. real=true prefers the per-message
 * usage in the transcript (R-102); otherwise tokens are estimated from text.
 * Returns null when the session has no assistant turn.
 */
export function claudeSessionRecord(text, opts) {
  opts = opts || {};
  const lines = String(text).split(/\r?\n/);
  let model = "", skill = "", description = "", workId;
  const est = { input: 0, output: 0, cacheRead: 0, cacheCreation: 0 };
  const real = { input: 0, output: 0, cacheRead: 0, cacheCreation: 0 };
  let sawAssistant = false, sawUsage = false;
  for (const line of lines) {
    if (!line.trim()) continue;
    let o; try { o = JSON.parse(line); } catch { continue; }
    if (o.type === "user" && o.message) {
      const t = textOf(o.message.content);
      if (t) {
        est.input += estimateTokens(t);
        if (!description && isRealPrompt(t)) description = shortDesc(t);
        const w = t.match(/context\/changes\/([A-Za-z0-9._-]+)/);
        if (w && !workId) workId = "context/changes/" + w[1];
        const sc = t.match(/(?:^|\s)\/(qa-[a-z0-9-]+)/);
        if (sc && !skill) skill = sc[1];
      }
    } else if (o.type === "assistant" && o.message) {
      sawAssistant = true;
      const m = o.message;
      if (m.model) model = m.model;
      const c = m.content;
      if (Array.isArray(c)) for (const b of c) {
        if (b && b.type === "text" && b.text) est.output += estimateTokens(b.text);
        if (b && b.type === "thinking" && b.thinking) est.output += estimateTokens(b.thinking);
        if (b && b.type === "tool_use" && b.name === "Skill" && b.input && b.input.skill && !skill) skill = b.input.skill;
      }
      const u = m.usage;
      if (u) {
        sawUsage = true;
        real.input += u.input_tokens || 0;
        real.output += u.output_tokens || 0;
        real.cacheRead += u.cache_read_input_tokens || 0;
        real.cacheCreation += u.cache_creation_input_tokens || 0;
      }
    }
  }
  if (!sawAssistant) return null;
  const useReal = !!opts.real && sawUsage;
  const tokens = useReal ? real : est;
  return {
    skill: skill || "(session)",
    description: description || "(no prompt captured)",
    model: model || "unknown",
    tokens,
    source: useReal ? "real" : "estimate",
    workId,
  };
}

// --- Copilot chat log → one session record (best-effort, estimate-only) ------
/**
 * One estimate record from a parsed VS Code Copilot chat-session object. The
 * format is undocumented and fragile (see the design record), so this is
 * defensive: unknown shapes yield null rather than throwing. Copilot is
 * estimator-only by design — no real cost path here.
 */
export function copilotSessionRecord(session) {
  try {
    const requests = Array.isArray(session && session.requests) ? session.requests : [];
    if (requests.length === 0) return null;
    let model = "", skill = "", description = "";
    const tokens = { input: 0, output: 0, cacheRead: 0, cacheCreation: 0 };
    for (const req of requests) {
      const userText = (req && req.message && (req.message.text ||
        (Array.isArray(req.message.parts) ? req.message.parts.map((p) => p && p.text || "").join(" ") : ""))) || "";
      if (userText) {
        tokens.input += estimateTokens(userText);
        if (!description) description = shortDesc(userText);
        const sc = userText.match(/(?:^|\s)\/(qa-[a-z0-9-]+)/);
        if (sc && !skill) skill = sc[1];
      }
      let respText = "";
      const resp = req && req.response;
      if (typeof resp === "string") respText = resp;
      else if (Array.isArray(resp)) respText = resp.map((r) => (r && (r.value || r.text)) || "").join(" ");
      if (respText) tokens.output += estimateTokens(respText);
      if (req && req.modelId && !model) model = req.modelId;
    }
    if (tokens.input === 0 && tokens.output === 0) return null;
    return {
      skill: skill || "(chat)",
      description: description || "(no prompt captured)",
      model: model || "gpt-4o",
      tokens,
      source: "estimate",
      workId: undefined,
    };
  } catch { return null; }
}

// --- filesystem discovery + main --------------------------------------------
function claudeProjectDir(root) {
  // Claude Code stores sessions under ~/.claude/projects/<cwd-slug>/, where the
  // slug is the absolute cwd with non-alphanumerics replaced by '-'.
  const slug = root.replace(/[^A-Za-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
  return join(homedir(), ".claude", "projects", slug);
}
function readJson(path) { try { return JSON.parse(readFileSync(path, "utf8")); } catch { return null; } }

function collectClaude(root) {
  const dir = claudeProjectDir(root);
  const out = [];
  if (!existsSync(dir)) return out;
  let files = [];
  try { files = readdirSync(dir).filter((f) => f.endsWith(".jsonl")); } catch { return out; }
  for (const f of files) {
    const sid = "claude:" + f.replace(/\.jsonl$/, "");
    let rec; try { rec = claudeSessionRecord(readFileSync(join(dir, f), "utf8"), { real: true }); } catch { rec = null; }
    if (rec) out.push(Object.assign({ platform: "claude", sid }, rec));
  }
  return out;
}
function collectCopilot(root) {
  const out = [];
  const appdata = process.env.APPDATA || join(homedir(), "AppData", "Roaming");
  const base = join(appdata, "Code", "User", "workspaceStorage");
  if (!existsSync(base)) return out;
  let hashes = [];
  try { hashes = readdirSync(base); } catch { return out; }
  for (const h of hashes) {
    // Only attribute a workspace whose recorded folder matches this repo.
    const meta = readJson(join(base, h, "workspace.json"));
    const folder = meta && (meta.folder || meta.workspace) || "";
    if (folder && !String(folder).replace(/\\/g, "/").includes(root.replace(/\\/g, "/"))) continue;
    const csDir = join(base, h, "chatSessions");
    if (!existsSync(csDir)) continue;
    let files = [];
    try { files = readdirSync(csDir).filter((f) => f.endsWith(".json")); } catch { continue; }
    for (const f of files) {
      const rec = copilotSessionRecord(readJson(join(csDir, f)));
      if (rec) out.push(Object.assign({ platform: "copilot", sid: "copilot:" + h + ":" + f }, rec));
    }
  }
  return out;
}

/** Merge freshly-derived session records into the per-user logs (one line per sid). */
export function mergeLogs(existingLines, fresh, user, anonymize) {
  const bySid = new Map();
  for (const line of existingLines) {
    let o; try { o = JSON.parse(line); } catch { continue; }
    if (o && o.sid) bySid.set(o.sid, o);
  }
  const nowIso = new Date().toISOString();
  for (const r of fresh) {
    const rec = {
      ts: (bySid.get(r.sid) && bySid.get(r.sid).ts) || nowIso,
      user, platform: r.platform, skill: r.skill, description: r.description,
      model: r.model, tokens: r.tokens, costUsd: costUsd(r.model, r.tokens),
      source: r.source, workId: r.workId, sid: r.sid,
    };
    bySid.set(r.sid, rec);
  }
  return [...bySid.values()];
}

function findRepoRoot() {
  // Prefer an explicit --root; else derive from this file's location
  // (<root>/context/telemetry/capture.mjs → up three).
  const arg = process.argv.indexOf("--root");
  if (arg >= 0 && process.argv[arg + 1]) return process.argv[arg + 1];
  return dirname(dirname(dirname(fileURLToPath(import.meta.url))));
}

function main() {
  try {
    const root = findRepoRoot();
    const telDir = join(root, "context", "telemetry");
    if (!existsSync(telDir)) { mkdirSync(telDir, { recursive: true }); }
    const manifest = readJson(join(root, "context", ".scaffold", "manifest.json")) || {};
    const anonymize = !!(manifest.choices && manifest.choices.anonymizeTelemetry);
    const email = gitConfig(root, "user.email");
    const user = anonymize ? anonymizeEmail(email) : (email || "unknown");
    const slug = anonymize ? anonymizeEmail(email) : emailSlug(email);

    const fresh = collectClaude(root).concat(collectCopilot(root)).map((r) => Object.assign({ user }, r));
    const logPath = join(telDir, slug + ".jsonl");
    const existing = existsSync(logPath) ? readFileSync(logPath, "utf8").split(/\r?\n/).filter(Boolean) : [];
    const merged = mergeLogs(existing, fresh, user, anonymize);
    if (merged.length > 0) {
      writeFileSync(logPath, merged.map((r) => JSON.stringify(r)).join("\n") + "\n", "utf8");
    }

    // Rebuild the aggregate from every per-user log in the area.
    const all = [];
    for (const f of readdirSync(telDir).filter((f) => f.endsWith(".jsonl"))) {
      for (const line of readFileSync(join(telDir, f), "utf8").split(/\r?\n/)) {
        if (!line.trim()) continue;
        let o; try { o = JSON.parse(line); } catch { continue; }
        if (o) all.push(o);
      }
    }
    writeFileSync(join(telDir, "index.json"), JSON.stringify(aggregateRecords(all), null, 2) + "\n", "utf8");
    process.stdout.write("telemetry: captured " + fresh.length + " session(s), " + all.length + " total record(s).\n");
  } catch (err) {
    process.stderr.write("telemetry: capture skipped (" + (err && err.message || err) + ")\n");
  }
}

// Run only when executed directly (not when imported by a test).
const invoked = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (invoked) main();
`;
