import type { LogicalSkill } from "./skills.js";

/**
 * Platform-agnostic content for the lean root config, the guideline docs, and the
 * `context/` system of record. All strings may carry `{{PLACEHOLDER}}` markers —
 * the scaffold orchestrator renders phase-1 vars and leaves the rest for phase 2.
 */

const BUCKET_TITLE: Record<LogicalSkill["bucket"], string> = {
  backbone: "Backbone — process & context",
  design: "Test design",
  automation: "Automation",
  analysis: "Analysis & data",
};

/**
 * The lean root "map" (~table of contents, not an encyclopedia). `invoke` is how
 * this platform refers to running a skill (e.g. "skill" vs "prompt").
 */
export function rootConfigMarkdown(skills: LogicalSkill[], invoke: string): string {
  const buckets: LogicalSkill["bucket"][] = ["backbone", "design", "automation", "analysis"];
  const skillList = buckets
    .map((b) => {
      const rows = skills
        .filter((s) => s.bucket === b)
        .map((s) => `- \`${s.name}\`${s.readOnly ? " *(read-only)*" : ""} — ${s.description}`)
        .join("\n");
      return `### ${BUCKET_TITLE[b]}\n${rows}`;
    })
    .join("\n\n");

  return `# QA orchestration — root map

> Lean index, not a manual. Knowledge lives in \`context/\`; pull it just-in-time.
> Generated by the QA-process scaffolder (phase 1). \`{{PLACEHOLDER}}\` markers are
> completed in phase 2 by the in-tool LLM. Keep this file short.

- **Stack:** {{PROJECT_LANGUAGE}} / {{BUILD_TOOL}}
- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Report language:** {{REPORT_LANGUAGE_NAME}}
- **Agent autonomy:** {{AUTONOMY_LEVEL}}
- **Generated:** {{GENERATED_AT}}

## Iron QA rule (non-negotiable — survives compaction)

> Every behavior under test ships with automated tests in **{{AUTOMATION_FRAMEWORK}}**.
> Every test case traces to an acceptance criterion. New behavior ⇒ new tests;
> changed behavior ⇒ updated tests. Work without passing tests is not done.

## How to work

1. Open or create a work-item with \`qa-new\` (id = \`<stream>-<slug>\`, stable).
2. Drive it: \`qa-ticket-review\` → \`qa-test-plan\`/\`qa-test-case-design\` → \`qa-automation-bootstrapper\`/\`qa-test-automate\` → run → \`qa-rca\` on failure → \`qa-review\` → \`qa-archive\`.
3. Run each step as a ${invoke}. State of record lives under \`context/\` — read it before acting, update it after.

## Skills

${skillList}

## Where things live

- \`context/foundation/\` — durable: test strategy, test plan, environments, tools, lessons, tech-debt tracker.
- \`context/changes/<work-id>/\` — in-flight work (work.md, plan.md, cases.md, automation.md).
- \`context/archive/<work-id>/\` — completed work (read-only history).
- \`context/reference/\` — reverse-engineered system docs (produced by \`qa-reverse-engineer\`).
- Guidelines — QA conventions & naming (see the guidelines files).
`;
}

/** Guideline documents (same content both platforms; only the path differs). */
export const GUIDELINES: Array<{ name: string; title: string; body: string }> = [
  {
    name: "qa-conventions",
    title: "QA conventions",
    body: `# QA conventions

> Phase 1 seeded this from the wizard. Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Static checks:** {{LINTERS}}

## Rules

{{QA_CONVENTIONS}}

## Test quality (non-negotiable)

- One behavior per test; deterministic, independent, parallel-safe — no sleeps.
- Cover negative and boundary cases, not just the happy path.
- Assert intended behavior, not a mirror of the implementation.
- Capture diagnostics on failure (trace/screenshot/log) at the paths recorded in \`context/foundation/tools.md\`.

## Project-specific conventions

> Record only non-obvious, project-specific rules an agent would otherwise get wrong.

{{PROJECT_SPECIFIC_CONVENTIONS}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it. Keep these short and real to this codebase.

✅ **Good** — one behavior, deterministic, waits on a condition, traces to an AC:
\`\`\`
test("returns 429 when the rate limit is exceeded", async () => {
  await sendRequests(limit + 1);
  await expect(lastResponse).toHaveStatus(429); // AC-3.1
});
\`\`\`

❌ **Avoid** — two behaviors, a fixed sleep, order-dependent state:
\`\`\`
test("rate limit", async () => {
  await sleep(2000);          // flaky: races the limiter
  expect(res.status).toBe(429);
  expect(user.isLoggedIn);    // unrelated second assertion
});
\`\`\`

## Applicable patterns

> Encouraged: name the design / programming / testing patterns this codebase applies
> (e.g. Page Object, Arrange-Act-Assert, Builder for test data) so agents follow them.

{{CONVENTIONS_PATTERNS}}
`,
  },
  {
    name: "test-naming",
    title: "Test naming",
    body: `# Test naming

> Phase 1 seeded this for **{{PROJECT_LANGUAGE}}** / **{{AUTOMATION_FRAMEWORK}}**.
> Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

## Conventions

- Test names state the behavior and expected outcome, e.g. \`returns 429 when rate limit exceeded\`.
- Case ids are stable and traceable to an acceptance criterion (e.g. \`AC-3.1\`).
- Files/specs mirror the feature under test, one feature area per file.

{{NAMING_RULES}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — states behavior + outcome, traceable to an AC:
- \`returns 429 when rate limit exceeded\` → AC-3.1
- \`rejects checkout when the cart is empty\` → AC-7.2

❌ **Avoid** — vague, numbered, or implementation-mirroring names:
- \`test1\`, \`testLogin\`, \`it("works")\`
- \`calls validateCart() then setStatus()\` (mirrors the code, not the behavior)

## Examples from this codebase

> Add a few real names from this codebase so agents copy the right pattern.

{{NAMING_EXAMPLES}}

## Applicable patterns

> Encouraged: naming patterns this codebase uses (e.g. Given-When-Then, "should…",
> one-feature-area-per-file) so agents copy the right shape.

{{NAMING_PATTERNS}}
`,
  },
  {
    name: "diagram-conventions",
    title: "Diagram conventions (Mermaid)",
    body: `# Diagram conventions (Mermaid)

> Phase 1 seeded this standard. Phase 2 adds the project-specific diagrams in the \`{{PLACEHOLDER}}\` section.

Diagrams in \`context/\` and in reports use **Mermaid** fenced code blocks, so they render in the tool and on the repo host, diff cleanly in version control, and never go stale as a binary image. Do not paste screenshots for an architecture or flow that could be Mermaid.

## Which diagram for what
- **\`flowchart\`** — process / decision flow (a test run, the daily loop, a triage path).
- **\`sequenceDiagram\`** — interactions over time (a request across services, an auth handshake); ideal for \`qa-rca\` reproductions and integration-test design.
- **\`stateDiagram-v2\`** — the lifecycle of an entity under test (order, session, work-item).
- **\`erDiagram\`** — data shapes when test data must match a schema (pairs with \`qa-test-data-gen\`).

## Rules
- Fence as \`\`\`mermaid; one diagram per block; declare direction (\`TD\`/\`LR\`) explicitly.
- Label every node and edge meaningfully. Keep a diagram to ~15 nodes — split a bigger one by domain rather than letting it sprawl.
- The diagram **supports** the prose and traceability; it never replaces the rule that every case traces to an acceptance criterion.
- Reference real source paths in the surrounding text; don't encode detail in the diagram that will drift from the code.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a fenced, directed, meaningfully labeled Mermaid flowchart:
\`\`\`mermaid
flowchart LR
  A[Acceptance criterion] --> B[Test case]
  B --> C[Automated test]
  C -->|fail| D[qa-rca]
  C -->|pass| E[qa-review]
\`\`\`

❌ **Avoid** — a pasted PNG screenshot (binary, rots, can't diff), or one
unlabeled 40-node blob with no declared direction. Don't paste an image for a
flow that could be Mermaid; split a sprawling diagram by domain instead.

## Applicable patterns

> Encouraged: diagram patterns this product favors (e.g. C4 levels for architecture,
> swimlanes for cross-team flows) so agents reach for the right shape.

{{DIAGRAM_PATTERNS}}

## Project-specific diagrams

> Add the canonical diagrams for this product (key user journeys, the system-context view) once known.

{{PROJECT_DIAGRAMS}}
`,
  },
  {
    name: "documentation-as-code",
    title: "Documentation as code",
    body: `# Documentation as code

> Phase 1 seeded this standard. Phase 2 records the project-specific doc workflow in the \`{{PLACEHOLDER}}\` section.

QA knowledge is treated like source code, not like a wiki. Everything under \`context/\` and the guideline docs lives **in the repo**, is **versioned** with the code it describes, is **reviewed in the same pull request** as the change it documents, is **validated deterministically** by \`doctor\` (structure, links, placeholders, the iron QA rule, the mandatory good/bad examples), and is **kept in sync via CI** — the same pipeline \`qa-ci-pipeline\` builds runs \`doctor\` so docs can't silently rot. "What's not in context doesn't exist": if it isn't written down here, the agent can't use it.

## Rules
- A behavior change and its docs land in **one PR**. Updating \`context/changes/<id>/\` or a guideline is part of the change, not a follow-up.
- Docs link out to real source paths and \`context/foundation/*\`; they never duplicate code or restate general testing advice. Link, don't copy.
- \`doctor\` is the gate, not a human eyeball: broken relative links, leftover phase-1 placeholders, a missing iron QA rule, or a guideline without good/bad examples are **errors** that fail the build.
- Plans are first-class artifacts: active work in \`context/changes/<id>/\`, completed work in \`context/archive/<id>/\` (read-only history). Don't delete history — supersede it.
- Run \`doctor\` in CI (wired by \`qa-ci-pipeline\`) so documentation drift fails the pipeline the same way a failing test does.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the doc changes ride with the code in the same reviewed, CI-checked PR:
\`\`\`
PR #142  "feat: rate-limit checkout (AC-3.1)"
  src/checkout/limiter.ts          (code)
  tests/checkout/limit.spec.ts     (test)
  context/changes/checkout-rate-limit/cases.md   (doc, traces AC-3.1)
  CI: doctor ✅  tests ✅  -> merge
\`\`\`

❌ **Avoid** — knowledge that lives outside the repo, or docs merged without validation:
\`\`\`
"the rate-limit details are in the Confluence page / a Slack thread"
context/foundation/tools.md links to ./does-not-exist.html   # broken link, no CI gate
\`\`\`

## Applicable patterns

> Encouraged: the doc-as-code practices this project applies (docs-in-PR, ADRs, \`doctor\` in CI,
> generated-from-source reference docs) so agents follow the same workflow.

{{DOCS_AS_CODE_PATTERNS}}

## Project-specific doc workflow

> Record this project's concrete workflow once known: where docs are reviewed, which CI job runs \`doctor\`, any doc owners.

{{PROJECT_DOC_WORKFLOW}}
`,
  },
];

/** The `context/` system of record laid down at scaffold time. */
export const FOUNDATION: Array<{ rel: string; body: string }> = [
  {
    rel: "context/foundation/test-strategy.md",
    body: `# Test strategy

> Durable. Filled by \`qa-init\` in phase 2. Keep lean; link out, don't duplicate.

- **Product under test:** {{PRODUCT_UNDER_TEST}}
- **Critical user journeys:** {{CRITICAL_JOURNEYS}}
- **Risk priorities:** {{RISK_PRIORITIES}}
- **Out of scope:** {{OUT_OF_SCOPE}}
`,
  },
  {
    rel: "context/foundation/test-plan.md",
    body: `# Test plan

> Durable. Owned by the \`test-plan\` skill.

- **Scope:** {{TEST_PLAN_SCOPE}}
- **Test levels & split:** {{TEST_LEVELS}}
- **Entry / exit criteria:** {{ENTRY_EXIT_CRITERIA}}
- **Tooling:** {{AUTOMATION_FRAMEWORK}}
- **Reporting cadence:** {{REPORTING_CADENCE}}
`,
  },
  {
    rel: "context/foundation/environments.md",
    body: `# Environments

> Durable. How to reach each test environment. "What's not in context doesn't exist."

- **Environments:** {{ENVIRONMENTS}}
- **Base URLs / endpoints:** {{BASE_URLS}}
- **Auth / credentials handling:** {{AUTH_HANDLING}}
- **Test data sources:** {{TEST_DATA_SOURCES}}
`,
  },
  {
    rel: "context/foundation/tools.md",
    body: `# Tools & result artifacts

> Durable. Records where test results live so skills can read outcomes directly.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Run command:** {{RUN_COMMAND}}
- **Report path:** {{REPORT_PATH}}
- **Trace / screenshot path:** {{TRACE_PATH}}
- **Machine-readable results (e.g. JUnit XML):** {{RESULTS_PATH}}
`,
  },
  {
    rel: "context/foundation/lessons.md",
    body: `# Lessons & golden rules

> Append-only playbook. \`qa-archive\` adds reusable lessons here so future runs
> don't repeat mistakes (flaky areas, data tricks, tooling gotchas).

{{LESSONS}}
`,
  },
  {
    rel: "context/foundation/tech-debt-tracker.md",
    body: `# Tech-debt tracker

> Durable, append-only — a first-class, versioned backlog of test debt and
> known-flaky areas. \`qa-archive\` appends entries as work-items close. Nothing
> here is auto-deleted: an item is resolved by linking the work-item that paid it
> down, not by removing the row, so the history of what we owed survives.

## Open test debt

> Each entry: id, area, what's owed, severity, and the work-item that found/introduced it.

{{TECH_DEBT}}

## Known flaky areas

> Tests or areas that fail intermittently — the quarantine reason and a link to the tracking work-item.

{{FLAKY_AREAS}}
`,
  },
  {
    rel: "context/reference/system-overview.md",
    body: `# System reference

> Durable. Produced by \`qa-reverse-engineer\` in phase 2 from the application source.
> For a large/monolith codebase the skill first proposes how to split this, then fills it.
> Covers: business context, architecture, data flow, integrations, entry points, test surface.
> Links out to real source paths — it does not duplicate code.

{{REVERSE_ENGINEERED_MAP}}
`,
  },
  {
    rel: "context/changes/.gitkeep",
    body: "",
  },
  {
    rel: "context/archive/.gitkeep",
    body: "",
  },
];
