import type { LogicalSkill } from "./skills.js";

/**
 * Platform-agnostic content for the lean root config, the guideline docs, and the
 * `context/` system of record. All strings may carry `{{PLACEHOLDER}}` markers —
 * the scaffold orchestrator renders phase-1 vars and leaves the rest for phase 2.
 */

const BUCKET_TITLE: Record<LogicalSkill["bucket"], string> = {
  backbone: "Backbone — process & context",
  design: "Test design",
  automation: "Automation",
  analysis: "Analysis & data",
};

/**
 * The lean root "map" (~table of contents, not an encyclopedia). `invoke` is how
 * this platform refers to running a skill (e.g. "skill" vs "prompt").
 */
export function rootConfigMarkdown(skills: LogicalSkill[], invoke: string): string {
  const buckets: LogicalSkill["bucket"][] = ["backbone", "design", "automation", "analysis"];
  const skillList = buckets
    .map((b) => {
      const rows = skills
        .filter((s) => s.bucket === b)
        .map((s) => `- \`${s.name}\`${s.readOnly ? " *(read-only)*" : ""} — ${s.description}`)
        .join("\n");
      return `### ${BUCKET_TITLE[b]}\n${rows}`;
    })
    .join("\n\n");

  return `# QA orchestration — root map

> Lean index, not a manual. Knowledge lives in \`context/\`; pull it just-in-time.
> Generated by the QA-process scaffolder (phase 1). \`{{PLACEHOLDER}}\` markers are
> completed in phase 2 by the in-tool LLM. Keep this file short.

- **Stack:** {{PROJECT_LANGUAGE}} / {{BUILD_TOOL}}
- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Report language:** {{REPORT_LANGUAGE_NAME}}
- **Agent autonomy:** {{AUTONOMY_LEVEL}}
- **Generated:** {{GENERATED_AT}}

## Iron QA rule (non-negotiable — survives compaction)

> Every behavior under test ships with automated tests in **{{AUTOMATION_FRAMEWORK}}**.
> Every test case traces to an acceptance criterion. New behavior ⇒ new tests;
> changed behavior ⇒ updated tests. Work without passing tests is not done.

## Grounding rule (non-negotiable — survives compaction)

> Ground every claim in a real, checkable artifact — cite \`file:line\`, a ticket
> id, or result-MCP output. Never invent files, paths, APIs, schemas, or test
> results; if you cannot cite it, say so and flag the uncertainty. A "passing"
> test you didn't observe pass is not evidence. What's not in context doesn't
> exist. See the \`grounding\` guideline.

{{MULTI_REPO_RULE}}## Read before you write (standing rule)

> Before any **write** skill changes a file, read the guidelines/standards that
> bear on the task — at minimum \`qa-conventions\` and \`test-naming\`, plus any that
> apply (\`spec-driven-development\`, \`grounding\`, \`assumptions\`,
> \`documentation-as-code\`, \`diagram-conventions\`). Don't act from memory: the standards live in the
> guideline files; pull them in first so the work conforms by construction
> instead of being corrected after. Composes with the grounding rule (read, don't
> recall) and documentation-as-code.

## How to work

1. Open or create a work-item with \`qa-new\` (id = \`<stream>-<slug>\`, stable).
2. Drive it: \`qa-ticket-review\` → \`qa-test-plan\`/\`qa-test-case-design\` → \`qa-automation-bootstrapper\`/\`qa-test-automate\` → run → \`qa-rca\` on failure → \`qa-review\` → \`qa-archive\`.
3. Run each step as a ${invoke}. State of record lives under \`context/\` — read it before acting, update it after.

## Skills

${skillList}

## Where things live

- \`context/foundation/\` — durable: test strategy, test plan, environments, tools, test-framework guide, framework-architecture (P3, generated), lessons, tech-debt tracker, repo map (test surface ↔ source).
- \`context/changes/<work-id>/\` — in-flight work (work.md, plan.md, cases.md, automation.md).
- \`context/refinements/\` — standalone ticket-refinement deliverables (\`.md\` + paste-ready \`.jira\`), produced by \`qa-ticket-review\` (no work-id required).
- \`context/archive/<work-id>/\` — completed work (read-only history).
- \`context/reference/\` — reverse-engineered system docs, the **P1** application pillar (produced by \`qa-reverse-engineer\`).
- \`context/knowledge/\` — durable domain knowledge, the **P2** requirements pillar synthesized from Jira/Confluence (produced by \`qa-knowledge\`).
- Guidelines — QA conventions & naming (see the guidelines files).
`;
}

/**
 * (R-091) Declarative deploy condition for a guideline. Absent ⇒ the guideline is
 * **universal** (always deployed). When present, the guideline deploys only if its
 * install context matches — evaluated in `scaffold` against the detected stack, the
 * wizard choices, and the workspace block (the same inputs `mcp.ts:resultServers`
 * switches on). Each listed dimension is an OR within itself; the object is an OR
 * across dimensions (any satisfied dimension deploys the guideline).
 */
export interface GuidelineWhen {
  /** Deploy if any detected automation framework is in this list. */
  frameworks?: string[];
  /** Deploy if the detected primary language is in this list (`node`/`java`/`python`). */
  language?: string[];
  /** Deploy if any detected performance tool is in this list (e.g. `jmeter`). */
  performance?: string[];
  /** Deploy if any detected security tool is in this list (e.g. `zap`) — R-055 dimension. */
  security?: string[];
  /** Deploy if any named MCP server is enabled in the wizard choices (e.g. `atlassian`/`xray`/`markitdown`). */
  mcp?: string[];
  /** Deploy if the install is a multi-repo workspace (a `workspace` block exists). */
  multiRepo?: boolean;
  /** Deploy if the app under test is a web app (future dimension; no signal yet). */
  web?: boolean;
}

/** A guideline document (same content both platforms; only the path differs). */
export interface Guideline {
  name: string;
  title: string;
  /**
   * The **lean** tier — the only content deployed into a target repo, loaded into
   * agent context just-in-time when a skill reads it. Keeps everything `doctor`
   * validates (H1, any contract sentence, the mandatory ✅/❌ examples, the phase-2
   * `{{PLACEHOLDER}}` slots).
   */
  body: string;
  /**
   * (R-090) Optional deeper material that, appended to the lean, forms the **full**
   * guide generated into `docs/guidelines/<name>.md` (full = `body ⊕ extended`, so
   * the full text contains the lean verbatim — duplication is impossible by
   * construction). **Never deployed** into a target repo; maintainer reference only.
   * When present, the deployed lean gains an inline-code pointer to the full guide.
   */
  extended?: string;
  /**
   * (R-091) Declarative deploy condition. Absent ⇒ universal (always deployed).
   * See {@link GuidelineWhen}.
   */
  when?: GuidelineWhen;
}

/** Where the generated **full** guides live in this package (maintainer reference, never deployed). */
export const GUIDELINE_DOCS_DIR = "docs/guidelines";

/**
 * (R-090) The inline-code pointer the deployed lean carries to its full guide. It
 * is **inline code, not a Markdown link** (the R-037 repo-map-inventory pattern),
 * so it can't trip `doctor`'s broken-relative-link check, and it is rendered **only
 * when the guideline actually has an `extended` tier** (no misleading "full guide"
 * pointer when lean == full).
 */
export function fullGuidePointer(name: string): string {
  return `\n> 📖 **Full guide** (maintainer reference — not loaded into agent context): \`${GUIDELINE_DOCS_DIR}/${name}.md\` carries this lean standard plus its deeper patterns and worked examples.\n`;
}

/**
 * (R-090) The guideline body as **deployed** into a target repo: the lean `body`,
 * plus the {@link fullGuidePointer} when (and only when) an `extended` tier exists.
 * Shared by `scaffold` (writes it) and `update` (diffs it), so the deployed shape
 * has one definition. Guidelines with no `extended` deploy byte-identically to the
 * raw body — which is every guideline until R-093 authors the first `extended`.
 */
export function deployedGuidelineBody(g: Guideline): string {
  return g.extended ? `${g.body}${fullGuidePointer(g.name)}` : g.body;
}

/** Guideline documents (same content both platforms; only the path differs). */
export const GUIDELINES: Guideline[] = [
  {
    name: "qa-conventions",
    title: "QA conventions",
    body: `# QA conventions

> Phase 1 seeded this from the wizard. Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Static checks:** {{LINTERS}}

## Rules

{{QA_CONVENTIONS}}

## Test quality (non-negotiable)

- One behavior per test; deterministic, independent, parallel-safe — no sleeps.
- Cover negative and boundary cases, not just the happy path.
- Assert intended behavior, not a mirror of the implementation.
- Capture diagnostics on failure (trace/screenshot/log) at the paths recorded in \`context/foundation/tools.md\`.

## Project-specific conventions

> Record only non-obvious, project-specific rules an agent would otherwise get wrong.

{{PROJECT_SPECIFIC_CONVENTIONS}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it. Keep these short and real to this codebase.

✅ **Good** — one behavior, deterministic, waits on a condition, traces to an AC:
\`\`\`
test("returns 429 when the rate limit is exceeded", async () => {
  await sendRequests(limit + 1);
  await expect(lastResponse).toHaveStatus(429); // AC-3.1
});
\`\`\`

❌ **Avoid** — two behaviors, a fixed sleep, order-dependent state:
\`\`\`
test("rate limit", async () => {
  await sleep(2000);          // flaky: races the limiter
  expect(res.status).toBe(429);
  expect(user.isLoggedIn);    // unrelated second assertion
});
\`\`\`

## Applicable patterns

> Encouraged: name the design / programming / testing patterns this codebase applies
> (e.g. Page Object, Arrange-Act-Assert, Builder for test data) so agents follow them.

{{CONVENTIONS_PATTERNS}}
`,
    extended: `## Extended — test code conventions

> Maintainer reference (generalized from the coding-standards source — generic parts only; the original is
> RestAssured/JUnit-specific). The lean tier above is the deployed contract.

### Test structure
- **One behavior per test.** A test name maps to a single acceptance criterion; if you need "and" in the
  name, split it. Arrange / act / assert reads top-to-bottom even when you don't enforce AAA blocks.
- **Independent & parallel-safe.** No shared mutable state between tests, no reliance on execution order,
  no fixed \`sleep\` — wait on a condition. (Composes with \`test-data-management\`.)

### Assertions
- **Assert intent, not the implementation.** Check the observable outcome (status, payload field, side
  effect), not a re-derivation of what the code does internally.
- **Fluent / structured assertions** over a bare boolean: \`expect(res).toHaveStatus(429)\` reports *what*
  failed and *what was expected*; \`assert res.ok\` reports only "false".
- **Hard vs soft.** Use a hard assertion when a later step is meaningless if it fails (e.g. status before
  body); use soft/grouped assertions to collect several independent field checks into one clear report.
- **Validate error responses too** — error status, error schema/shape, and message — not just the 2xx path.

### Setup / teardown & resources
- Acquire in setup, release in teardown (or fixture scope); every created resource is cleaned up even when
  the test fails (try/finally or the framework's fixture teardown). Never leak a connection, file, or row.

### Import / formatting hygiene
- Imports are grouped and ordered by the formatter, not hand-sorted (see \`code-formatting\`); a logic diff
  should never carry import churn.

### ✅ / ❌
- ✅ deterministic, one behavior, fluent assertion on the outcome, cleans up in \`finally\`, traces an AC.
- ❌ two behaviors in one test, a fixed \`sleep\`, \`assert res.status == 200\` with no diagnostic, leaked state.
`,
  },
  {
    name: "grounding",
    title: "Grounding & anti-hallucination",
    body: `# Grounding & anti-hallucination

> Phase 1 seeded this standard. Phase 2 records this project's ground-truth sources in the \`{{PLACEHOLDER}}\` section.

Every claim an agent makes about this system — a path, an API, a schema, a requirement, a test result — must be grounded in a real, checkable artifact. Inventing a plausible-looking file path, function name, or "passing" result is worse than admitting you don't know: it poisons \`context/\` and sends the next run down a dead end. "What's not in context doesn't exist": if you can't read it or cite it, treat it as unknown.

## Rules
- **Cite the source of every factual claim.** Reference \`file:line\`, a ticket id (e.g. Jira \`PROJ-123\`), or the result-MCP output you read it from. A claim with no citable source is a hypothesis — label it as one.
- **Never invent files, paths, APIs, schemas, or results.** If a path or symbol might exist, open it and confirm before relying on it; don't assert a test passed without reading the run's result artifact.
- **Flag uncertainty explicitly.** Write "I could not find…" or "unverified" rather than filling the gap with a confident guess. When you must infer, legalize it in a \`## Assumptions\` table (see the \`assumptions\` guideline) — inference outside that table is a hallucination. Surfacing a gap is a finding; hiding it is a defect.
- **Prefer reading over recalling.** Pull the artifact in (source, ticket, trace, JUnit XML via the result MCP) instead of relying on memory or training priors — especially for versions, paths, and API shapes that drift.
- This reinforces, never weakens, the iron QA rule: a "passing" test you did not actually observe pass is not evidence.

## Evidence types (ranked — strongest first)

Not all citations are equal. Prefer the strongest available source; reach down the list only when nothing higher exists, and mark the weaker ones as such.

| Rank | Evidence type | Citation form | Strength |
|---|---|---|---|
| 1 | Source code | \`path/file.ext#L120-L140\` | Strongest — deterministic, the system's own truth |
| 2 | Config / infrastructure | \`path/application.yml#L10-L20\` | Strong — deterministic |
| 3 | Test evidence | \`path/SomeTest.ext#L45-L60\` | Strong — documents intended behavior |
| 4 | Result-MCP / run artifact | \`playwright-results: test-results/auth-login\`, a JUnit XML row | Strong — the only truth about a *run* |
| 5 | Ticket / spec (MCP) | Jira \`PROJ-123\`, a Confluence page | Strong — authoritative for requirements |
| 6 | Existing doc in \`context/\` | \`context/reference/…#L-L\` | Medium — secondary, may be stale |
| 7 | Git history | \`git log <file>\` excerpt | Medium — historical context |
| 8 | External doc (URL) | \`https://…\` | Weak — volatile; verify before relying |
| 9 | User quote | "User said: …" | Authoritative *only* for user-provided facts |

## Minimum context for code citations (≥ 10 lines)

A citation must let a reader verify the claim **without reopening the file**. When citing code for a non-trivial claim, give a line *range* covering at least ~10 lines (or the whole method if shorter) — not a bare filename, not a single line ripped from its context. \`src/auth/login.ts#L42-L58\` is verifiable; \`login.ts\` is not. Trim a long method to the relevant 10–40 lines rather than pasting the whole file.

## Identifier scrub (before anything ships)

Before finalizing any output, list every proper noun and identifier in it and confirm each is real — this is where hallucinations hide:
- [ ] **Class / method / function names** — a search returns a match.
- [ ] **Endpoint paths** — match a controller annotation / route / OpenAPI entry.
- [ ] **Environment variables** — present in config or documented.
- [ ] **Ticket / test keys** (Jira, Xray) — fetched via MCP, never guessed.
- [ ] **File paths** — confirmed to exist (the broken-link check and \`doctor\` catch these in \`context/\`).

An identifier you cannot confirm is either an assumption (move it to the \`assumptions\` table) or a hallucination (drop it).

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — claims carry citations, and the gap is named instead of guessed:
\`\`\`
Empty-password login is rejected by validateCredentials (src/auth/login.ts:42),
tracing to AC PROJ-217. Its e2e test passed this run — read via the
playwright-results MCP (test-results/auth-login). I could not find any test for
the lockout-after-5-tries path; flagging it as uncovered, not assuming covered.
\`\`\`

❌ **Avoid** — confident, uncited, invented; no artifact was opened:
\`\`\`
Login is handled in src/auth/AuthService.login() and all auth tests pass.
\`\`\`

## Applicable patterns

> Encouraged: name the grounding practices this project relies on (cite-by-\`file:line\`,
> result-MCP as the only source of run truth, ticket-id traceability) so agents follow them.

{{GROUNDING_PATTERNS}}

## Project-specific ground-truth sources

> Record where this project's ground truth lives (the schema/SDK of record, the ticket system, the canonical result dirs) so agents read it instead of guessing.

{{PROJECT_GROUNDING_SOURCES}}
`,
    extended: `## Extended — anti-hallucination checklists

> Maintainer reference (adapted from the anti-hallucination / verification-steps source). The lean tier
> above is the deployed contract. Not loaded into agent context.

### Pre-completion verification (run before finishing any analysis or doc)
- **Classes & methods** — every class/method named exists (a search returns a match); no invented
  utility classes or helpers; imports/packages resolve.
- **Versions** — every version comes from a manifest you read (\`package.json\` / \`pom.xml\` / \`go.mod\` /
  \`requirements.txt\`), never an assumed or "typical" number.
- **Endpoints** — every endpoint verified in the controller/handler/route source; HTTP method and path
  match the actual annotation/decorator; request/response types confirmed.
- **Configuration** — env vars and property names exist in the real config; default values read, not assumed.
- **Integration points** — external-service client classes exist; integration URLs verified in config;
  the auth mechanism confirmed in code.
- **Source references** — every claim carries a \`file:line\`; the line numbers are accurate and the
  snippet matches the file.

### Red-flag phrases (each demands verification before it ships)
| Phrase | Action |
|---|---|
| "Typically uses…" | Verify in source |
| "Standard pattern is…" | Find a real example in the codebase |
| "Should have…" | Confirm it exists |
| "Probably configured…" | Read the actual config |
| "Similar to other services…" | Verify that specific service |
| "Common approach…" | Find the documented pattern |

These are the same "common practice" tells the \`assumptions\` guideline bans as a *basis*: if a sentence
leans on one, it is either an assumption (move it to the \`## Assumptions\` table with a real basis) or a
hallucination (drop it).

### Source-of-truth ordering
When two sources disagree, trust the one higher in the lean tier's evidence-type table: **source code >
config > test > result-MCP > ticket > existing doc > git > web > user recollection**. A doc in
\`context/\` can be stale; the code cannot. Never silently pick a winner — record the conflict
(\`[Conflicting sources: A says X, B says Y]\`) and resolve it explicitly.
`,
  },
  {
    name: "assumptions",
    title: "Assumptions protocol",
    body: `# Assumptions protocol

> Phase 1 seeded this standard. Phase 2 records this project's assumption workflow in the \`{{PLACEHOLDER}}\` section.

The \`grounding\` rule says cite a real artifact for every claim. This guideline covers the other half: what to do when you *must* infer something you cannot yet cite. Inference is **allowed only** inside an explicit \`## Assumptions\` table, where each row carries its basis, impact, a way to verify it, and a calibrated confidence — so the reader can accept, challenge, or verify it. Any inferred content **outside** the table is treated as a hallucination, exactly as the \`grounding\` rule treats an uncited claim. This legalizes the unavoidable guess by making it visible and checkable, instead of letting it masquerade as fact.

## The Assumptions table

Every document or report that contains any inferred claim MUST include a \`## Assumptions\` table:

\`\`\`markdown
## Assumptions

| ID | Claim | Basis | Impact | Verification | Confidence |
|----|-------|-------|--------|--------------|------------|
| A1 | partnerKey follows a "COUNTRY-BRAND" format | \`ServiceImpl.java:44\` calls \`extractValuesFromKey(partnerKey).get("country")\` | Test-data shape; invalid format ⇒ failing integration tests | Read \`extractValuesFromKey\` impl; ask the dev team for the validation rule | medium |
\`\`\`

### Column rules

| Column | Required content |
|---|---|
| **ID** | \`A1\`, \`A2\`, … sequential per document. |
| **Claim** | One sentence stating exactly what is being assumed. |
| **Basis** | Concrete evidence (\`file:line\`, MCP source, user quote) that *suggested* the inference. **Never** "common practice" / "typical pattern" / "usually" — those are red flags, not a basis. |
| **Impact** | The downstream decision that depends on this assumption (what breaks if it's wrong). |
| **Verification** | A specific action — a file to read, a command to run, a person to ask — that would confirm or refute it. |
| **Confidence** | \`low\` / \`medium\` / \`high\`, calibrated (see below), not optimistic. |

## Confidence calibration

| Confidence | Meaning |
|---|---|
| **high** | A single missing fact, strongly implied by the surrounding evidence; verification would take under five minutes. |
| **medium** | Several plausible readings; you chose one with documented reasoning. |
| **low** | Speculative; the work proceeds but the reader is warned. |

If you would mark **high** for half your rows or more, recalibrate — **high confidence is rare**.

## Reference convention

When the body relies on an assumption, cite it inline as \`(A1)\` so the assumption and its use stay linked:

\`\`\`markdown
The lead service exposes a bulk endpoint (A1) the ticket must extend with retry logic (A3).
\`\`\`

Every inline \`(An)\` must resolve to a row in the table, and every row should be referenced at least once.

## When NOT to use an assumption

The table legalizes *grounded inference*, not laundering. Do **not** use it for:
- A pure guess with no basis → write \`[Required input — not provided]\` and stop, don't invent a basis.
- Something the user actually told you → cite the user, it is not an assumption.
- Something already in a workspace file → cite \`file:line\`, it is a fact, not an assumption.
- Conflicting sources → write \`[Conflicting sources: A says X, B says Y]\`, don't silently pick one.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the inference is in the table with a concrete basis and a calibrated confidence, and the body references it:
\`\`\`markdown
Auth is delegated to the gateway (A2), so the service has no login test surface.

## Assumptions
| ID | Claim | Basis | Impact | Verification | Confidence |
|----|-------|-------|--------|--------------|------------|
| A2 | The service delegates auth to the API gateway | No \`SecurityConfig\` and no \`@PreAuthorize\` in \`src/main/java\` | No auth cases needed for this service | Check the gateway config; ask DevOps | medium |
\`\`\`

❌ **Avoid** — an unmarked inference stated as fact, justified by "common practice", no way to verify:
\`\`\`markdown
The service uses a 30-second timeout (Spring's default) and authenticates via the gateway.
\`\`\`

## Applicable patterns

> Encouraged: the assumption practices this project relies on (a single \`## Assumptions\` table per report,
> \`(An)\` inline references, a review step that rejects uncited inference) so agents follow them.

{{ASSUMPTIONS_PATTERNS}}

## Project-specific assumptions workflow

> Record where this project tracks assumptions and how they're validated (the doc/section assumptions live in, who signs off on a \`high\`, how a refuted assumption is retired) once known.

{{PROJECT_ASSUMPTIONS_WORKFLOW}}
`,
    extended: `## Extended — zero-tolerance protocol

> Maintainer reference (adapted from the assumptions-rules source). The lean tier above is the deployed
> contract. Not loaded into agent context.

### The golden rule
**Zero tolerance for undocumented assumptions.** Any claim not directly readable from a workspace artifact
is an assumption, and every assumption is either documented in the \`## Assumptions\` table or removed.
There is no third option — an undocumented inference stated as fact is a defect, not a stylistic choice.

### What counts as an assumption
- A data format, range, or unit you inferred rather than read.
- A behavior "implied" by a name (\`partnerKey\` → "COUNTRY-BRAND format") but not confirmed in code.
- An integration, ownership, or dependency you concluded from indirect evidence.
- A default value, timeout, or limit you "know" from the framework rather than from this project's config.

### Worked example (the table in use)
\`\`\`markdown
## Assumptions
| ID | Claim | Basis | Impact | Verification | Confidence |
|----|-------|-------|--------|--------------|------------|
| A1 | partnerKey follows a "COUNTRY-BRAND" format | ServiceImpl.java:44 calls extractValuesFromKey(partnerKey).get("country") | Test data shape; an invalid key fails integration tests | Read extractValuesFromKey; ask the dev team for the validation regex | medium |
\`\`\`
The body then references it: "The lookup keys on country (A1)."

### Common scenarios that REQUIRE a row
- Reverse-engineering a service whose spec is incomplete.
- Designing cases for an acceptance criterion that is ambiguous.
- Root-causing a failure where the intended behavior isn't written down.
- Generating test data whose valid/invalid boundaries aren't specified.

### Consequences of skipping it
An undocumented assumption that turns out wrong silently poisons everything downstream — cases trace to a
requirement that doesn't exist, automation asserts behavior the system never promised, a refinement
recommends work that isn't needed. The table is cheap; the silent wrong guess is expensive. **High
confidence is rare** — if half your rows are \`high\`, recalibrate.
`,
  },
  {
    name: "test-naming",
    title: "Test naming",
    body: `# Test naming

> Phase 1 seeded this for **{{PROJECT_LANGUAGE}}** / **{{AUTOMATION_FRAMEWORK}}**.
> Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

## Conventions

- Test names state the behavior and expected outcome, e.g. \`returns 429 when rate limit exceeded\`.
- Case ids are stable and traceable to an acceptance criterion (e.g. \`AC-3.1\`).
- Files/specs mirror the feature under test, one feature area per file.

{{NAMING_RULES}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — states behavior + outcome, traceable to an AC:
- \`returns 429 when rate limit exceeded\` → AC-3.1
- \`rejects checkout when the cart is empty\` → AC-7.2

❌ **Avoid** — vague, numbered, or implementation-mirroring names:
- \`test1\`, \`testLogin\`, \`it("works")\`
- \`calls validateCart() then setStatus()\` (mirrors the code, not the behavior)

## Examples from this codebase

> Add a few real names from this codebase so agents copy the right pattern.

{{NAMING_EXAMPLES}}

## Applicable patterns

> Encouraged: naming patterns this codebase uses (e.g. Given-When-Then, "should…",
> one-feature-area-per-file) so agents copy the right shape.

{{NAMING_PATTERNS}}
`,
    extended: `## Extended — naming patterns by element

> Maintainer reference (generalized from the naming-convention source — the originals are JVM-specific;
> apply the *shape*, not the exact casing, to your stack). The lean tier above is the deployed contract.

| Element | Pattern | Example |
|---|---|---|
| **Test class / suite** | \`<FeatureOrEndpoint>Test\` / \`<feature>.spec\` — names the unit under test, not "Tests1" | \`CheckoutRateLimitTest\`, \`checkout-rate-limit.spec.ts\` |
| **Test method / case** | states *behavior + condition + outcome*; verb-led, no \`test\` prefix noise | \`returns429WhenRateLimitExceeded\`, \`rejects checkout when cart is empty\` |
| **Test-data variable** | describes the *role*, not the type | \`expiredCard\`, \`adminUser\` — not \`obj\`, \`data2\` |
| **Constant** | \`UPPER_SNAKE\` for fixed values, grouped by domain | \`MAX_RETRIES\`, \`DEFAULT_CURRENCY\` |
| **Schema / model** | mirrors the contract entity | \`CheckoutRequest\`, \`OrderResponse\` |
| **Package / folder** | mirrors the feature area, one area per folder | \`tests/checkout/\`, \`tests/auth/\` |

### Rules behind the table
- **The name is the spec.** A reader who sees only the test name should know what behavior is verified and
  under what condition — that is what makes a failing test report self-explanatory.
- **Don't mirror the implementation.** \`callsValidateThenSetStatus\` couples the name to today's code;
  \`rejectsExpiredCard\` couples it to the behavior, which is what the AC promised. Composes with
  \`spec-driven-development\` (the name traces to the criterion, not the call graph).
- **One feature area per file**, so a change touches one place and the suite stays navigable.
- **Stable case ids** (\`AC-3.1\` → \`TC-12\`) survive renames and carry the traceability the iron QA rule needs.

### ✅ / ❌
- ✅ \`returns 404 when the order id is unknown\` → traces \`AC-2.4\`
- ❌ \`test1\`, \`testCheckout\`, \`it("works")\`, \`verifyOrderServiceLogicPath\`
`,
  },
  {
    name: "diagram-conventions",
    title: "Diagram conventions (Mermaid)",
    body: `# Diagram conventions (Mermaid)

> Phase 1 seeded this standard. Phase 2 adds the project-specific diagrams in the \`{{PLACEHOLDER}}\` section.

Diagrams in \`context/\` and in reports use **Mermaid** fenced code blocks, so they render in the tool and on the repo host, diff cleanly in version control, and never go stale as a binary image. Do not paste screenshots for an architecture or flow that could be Mermaid.

## Which diagram for what
- **\`flowchart\`** — process / decision flow (a test run, the daily loop, a triage path).
- **\`sequenceDiagram\`** — interactions over time (a request across services, an auth handshake); ideal for \`qa-rca\` reproductions and integration-test design.
- **\`stateDiagram-v2\`** — the lifecycle of an entity under test (order, session, work-item).
- **\`erDiagram\`** — data shapes when test data must match a schema (pairs with \`qa-test-data-gen\`).
- **C4 (\`C4Context\`/\`C4Container\`/\`C4Component\`)** — system architecture in \`context/reference/\` (produced by \`qa-reverse-engineer\`); see the C4 mapping below.

## Architecture diagrams — the C4 model
Architecture docs in \`context/reference/\` use the **C4 model**: four levels of zoom, each its own
diagram, so a reader picks the altitude the testing question needs. Map each level to a diagram type:

| C4 level | Scope | Mermaid diagram |
|---|---|---|
| **L1 — System Context** | the system as one box + its users and the external systems it talks to | \`C4Context\` (portable fallback: \`flowchart\`) |
| **L2 — Container** | the deployable/runnable units inside the system boundary (apps, services, data stores, queues) | \`C4Container\` (fallback: \`flowchart\`) |
| **L3 — Component** | the components inside one (testing-critical) container + their entry points | \`C4Component\` (fallback: \`flowchart\`) |
| **L4 — Code** | classes/functions inside a component — usually skipped; generate on demand | \`classDiagram\` (a few key types only) |

- Zoom in only as far as the testing question needs — most QA work lives at **L1–L3**.
- Mermaid's \`C4*\` blocks are the native fit; if a renderer lacks C4 support, fall back to a labeled \`flowchart\` with the same boxes/edges.
- **Don't hand-maintain L4** — it drifts from the code. Link to the source instead (per the \`grounding\` rule).

<!-- @formatter:off -->
\`\`\`mermaid
C4Context
  title System context — checkout
  Person(customer, "Customer", "Buys items")
  System(shop, "Shop", "Sells items online")
  System_Ext(psp, "Payment provider", "Charges cards")
  Rel(customer, shop, "Browses & buys")
  Rel(shop, psp, "Authorizes payment")
\`\`\`
<!-- @formatter:on -->

## Rules
- Fence as \`\`\`mermaid; one diagram per block; declare direction (\`TD\`/\`LR\`) explicitly.
- **Wrap every rendered diagram in \`@formatter:off\` / \`@formatter:on\` guards** (the HTML-comment form in Markdown) so an autoformatter can't reflow the fence and break the render — see the \`code-formatting\` guideline. Diagrams are born compliant.
- Label every node and edge meaningfully. Keep a diagram to ~15 nodes — split a bigger one by domain rather than letting it sprawl.
- The diagram **supports** the prose and traceability; it never replaces the rule that every case traces to an acceptance criterion.
- Reference real source paths in the surrounding text; don't encode detail in the diagram that will drift from the code.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a fenced, directed, meaningfully labeled Mermaid flowchart, wrapped in \`@formatter:off\` guards (per \`code-formatting\`) so an autoformat pass can't reflow it:
<!-- @formatter:off -->
\`\`\`mermaid
flowchart LR
  A[Acceptance criterion] --> B[Test case]
  B --> C[Automated test]
  C -->|fail| D[qa-rca]
  C -->|pass| E[qa-review]
\`\`\`
<!-- @formatter:on -->

❌ **Avoid** — a pasted PNG screenshot (binary, rots, can't diff), or one
unlabeled 40-node blob with no declared direction. Don't paste an image for a
flow that could be Mermaid; split a sprawling diagram by domain instead.

## Applicable patterns

> Encouraged: diagram patterns this product favors (e.g. C4 levels for architecture,
> swimlanes for cross-team flows) so agents reach for the right shape.

{{DIAGRAM_PATTERNS}}

## Project-specific diagrams

> Add the canonical diagrams for this product (key user journeys, the system-context view) once known.

{{PROJECT_DIAGRAMS}}
`,
    extended: `## Extended — deeper diagram rules

> Maintainer reference (adapted from the diagram-standards source). The lean tier above is the deployed
> contract; this records the failure modes that motivate it. Not loaded into agent context.

### Forbidden: \`classDef\` styling
Do **not** use \`classDef name fill:#…,stroke:#…\` + \`class A,B name\` in committed Mermaid — it is the
single most common cause of broken diagrams:
- **Parser conflicts** — \`classDef\` with style properties fails outright in several renderers.
- **Keyword conflicts** — style names like \`error\` / \`warning\` / \`info\` collide with Mermaid keywords.
- **Line breaking** — an editor wraps a long \`classDef\` line and corrupts the hex colour, breaking the render.
- **Version drift** — different Mermaid versions render the same \`classDef\` differently, or not at all.

Convey meaning through **structure** instead — subgraphs to group, a \`rect rgb(…)\` block to shade a
region (e.g. an error path), node shapes (\`[ ]\` / \`( )\` / \`{ }\`) for kind, and \`%% comments\` for intent.
If colour is genuinely required, prefer \`%%{init: {'theme':'base'}}%%\` over per-node \`classDef\`.

### Node verification (composes with \`grounding\`)
Every node or label that names a real class, service, endpoint, or file must be **verified to exist**
before it ships — a diagram is a claim like any other. An invented box in an architecture diagram is a
hallucination; confirm it in the source and cite the path in the surrounding prose.

### Why the formatter guards are mandatory
Editors auto-format Markdown on save/commit: they add spaces after colons/commas and reflow indentation,
each of which breaks a Mermaid fence. The \`<!-- @formatter:off -->\` … \`<!-- @formatter:on -->\` pair is
ignored by Markdown renderers but respected by formatters (see \`code-formatting\`). An unprotected diagram
is a review reject.

### Validation checklist (before commit)
- [ ] Diagram is fenced as a \`mermaid\` block and wrapped in \`@formatter:off\` / \`@formatter:on\`.
- [ ] No \`classDef … fill:\` / \`class … ;\` styling.
- [ ] Direction declared (\`TD\` / \`LR\`); every node and edge labelled.
- [ ] ≤ ~15 nodes (else split by domain); every real identifier verified in source.
- [ ] One diagram per fence; the C4 level matches the doc (see the C4 table in the lean tier).
`,
  },
  {
    name: "documentation-as-code",
    title: "Documentation as code",
    body: `# Documentation as code

> Phase 1 seeded this standard. Phase 2 records the project-specific doc workflow in the \`{{PLACEHOLDER}}\` section.

QA knowledge is treated like source code, not like a wiki. Everything under \`context/\` and the guideline docs lives **in the repo**, is **versioned** with the code it describes, is **reviewed in the same pull request** as the change it documents, is **validated deterministically** by \`doctor\` (structure, links, placeholders, the iron QA rule, the mandatory good/bad examples), and is **kept in sync via CI** — the same pipeline \`qa-ci-pipeline\` builds runs \`doctor\` so docs can't silently rot. "What's not in context doesn't exist": if it isn't written down here, the agent can't use it.

## Rules
- A behavior change and its docs land in **one PR**. Updating \`context/changes/<id>/\` or a guideline is part of the change, not a follow-up.
- Docs link out to real source paths and \`context/foundation/*\`; they never duplicate code or restate general testing advice. Link, don't copy.
- \`doctor\` is the gate, not a human eyeball: broken relative links, leftover phase-1 placeholders, a missing iron QA rule, or a guideline without good/bad examples are **errors** that fail the build.
- Plans are first-class artifacts: active work in \`context/changes/<id>/\`, completed work in \`context/archive/<id>/\` (read-only history). Don't delete history — supersede it.
- Run \`doctor\` in CI (wired by \`qa-ci-pipeline\`) so documentation drift fails the pipeline the same way a failing test does.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the doc changes ride with the code in the same reviewed, CI-checked PR:
\`\`\`
PR #142  "feat: rate-limit checkout (AC-3.1)"
  src/checkout/limiter.ts          (code)
  tests/checkout/limit.spec.ts     (test)
  context/changes/checkout-rate-limit/cases.md   (doc, traces AC-3.1)
  CI: doctor ✅  tests ✅  -> merge
\`\`\`

❌ **Avoid** — knowledge that lives outside the repo, or docs merged without validation:
\`\`\`
"the rate-limit details are in the Confluence page / a Slack thread"
context/foundation/tools.md links to ./does-not-exist.html   # broken link, no CI gate
\`\`\`

## Applicable patterns

> Encouraged: the doc-as-code practices this project applies (docs-in-PR, ADRs, \`doctor\` in CI,
> generated-from-source reference docs) so agents follow the same workflow.

{{DOCS_AS_CODE_PATTERNS}}

## Project-specific doc workflow

> Record this project's concrete workflow once known: where docs are reviewed, which CI job runs \`doctor\`, any doc owners.

{{PROJECT_DOC_WORKFLOW}}
`,
  },
  {
    name: "documentation",
    title: "Documentation standard",
    body: `# Documentation standard

> Phase 1 seeded this standard. Phase 2 records this project's doc conventions in the \`{{PLACEHOLDER}}\` section.

Every document this orchestration generates — a foundation doc, a reference/knowledge pillar, a refinement, a runtime artifact under \`context/changes/\` — conforms to **one shape**, so the whole \`context/\` system of record is uniform and machine-checkable. This is the meta-standard the pillars rest on. It does **not** restate the rules other guidelines already own; it **composes** them and adds the four structural rules that make a generated doc parseable. It references — never duplicates — \`grounding\` (every claim cites a real artifact), \`diagram-conventions\` (diagrams are Mermaid, fenced and guarded), and \`documentation-as-code\` (docs are versioned in-repo, reviewed in PR, and gated by \`doctor\` in CI).

## Two tiers (read from the path)
A document's tier is read from where it lives, so \`doctor\` checks the right contract:
- **Durable docs** — \`context/foundation/\`, \`context/reference/\` (P1), \`context/knowledge/\` (P2), \`context/refinements/\` (P2). The long-lived structural map of the system. Get the **full** standard below.
- **Runtime artifacts** — \`context/changes/<work-id>/*\`. The trace of one unit of work; their shape lives in the artifact registry (\`work\`/\`plan\`/\`cases\`/\`automation\`/…). Get the **light** standard.

## The full standard (durable docs)
- **YAML frontmatter** at the very top, between \`---\` fences, carrying at least:
  | Key | Meaning |
  |-----|---------|
  | \`title\` | the document's human title (matches the H1) |
  | \`version\` | semver of the doc, bumped on a substantive edit |
  | \`last-updated\` | ISO date of the last substantive edit |
  | \`owner-skill\` | the skill responsible for keeping it current |
  | \`status\` | \`seeded\` (phase-1 skeleton) → \`draft\` → \`current\` |
- **A single H1.** Exactly one \`#\` heading — the document title — then a strict \`##\` → \`###\` hierarchy. Never a second H1; never skip a level.
- **"When to use this document."** An opening lede (the \`>\` blockquote the seeded docs carry) that says in one or two sentences when a reader should reach for this doc and what they'll get — so an agent pulls the right doc just-in-time instead of reading everything.
- **Length discipline (anti-bloat).** A doc earns its length. Link out to source (\`grounding\`) and to sibling docs instead of restating them; a foundation/reference doc that grows past ~1–2 screens of prose is a smell — split it (by C4 level, by the repo map, or by domain) rather than letting it sprawl. "What's not in context doesn't exist" is not a licence to write everything down: record what an agent can't infer, link the rest.

## The light standard (runtime artifacts)
- Frontmatter carries \`status\` (the work-item lifecycle the validator gates on) and the \`work-id\`; the rest of the shape is the trace markers (\`AC<n>\` / \`Traces to:\` / \`Covers:\`) and the \`requiredSections\` the artifact registry defines. Don't bolt the durable five-key frontmatter onto a runtime artifact — its provenance lives in the registry, not in frontmatter.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a durable doc with conformant frontmatter, one H1, a when-to-use lede, and a link instead of a restatement:
\`\`\`markdown
---
title: System reference — C4 index
version: 1.2.0
last-updated: 2026-06-25
owner-skill: qa-reverse-engineer
status: current
---
# System reference — C4 index

> Read this first to orient on the architecture before planning tests; it links to the C4 levels and the test surface.

## Architecture (C4)
- L1 — System context: [c4-context.md](./c4-context.md)   <!-- link, don't restate -->
\`\`\`

❌ **Avoid** — no frontmatter, two H1s, a wall of prose that duplicates the source instead of citing it:
\`\`\`markdown
# Overview
…three screens restating what AuthService already does, with no file:line citation…
# Also the database            <!-- second H1; should be a ## under one title -->
\`\`\`

## Applicable patterns

> Encouraged: the doc patterns this project standardizes on (a frontmatter linter, a docs ToC,
> "one concept per file", generated-from-source reference docs) so agents follow them.

{{DOCUMENTATION_PATTERNS}}

## Project-specific documentation workflow

> Record this project's concrete conventions once known: where the doc version/owner registry lives, the
> max-length rule you enforce, and who signs off a \`status: current\`.

{{PROJECT_DOCUMENTATION_WORKFLOW}}
`,
    extended: `## Extended — documentation hierarchy & content standards

> Maintainer reference (adapted from the project-documentation source). The lean tier above is the deployed
> contract (the machine-checkable shape); this records the human conventions around it.

### Documentation hierarchy (read top-down)
1. **Entry point** — a root \`README\` that orients a newcomer and links onward; it never duplicates the
   detail below it.
2. **Durable structural docs** — \`context/foundation/\` (strategy, framework, environments, repo map),
   \`context/reference/\` (P1 system docs, C4), \`context/knowledge/\` (P2 domain). The long-lived map.
3. **Runtime artifacts** — \`context/changes/<work-id>/\` (plan/cases/automation), the trace of one unit of work.
A reader pulls the **right altitude** for their question; an agent reads the lede to decide, then the doc.

### Single source of truth
Each fact lives in **exactly one** doc and is **linked**, never copied. A duplicated fact is a future
contradiction — when one copy is updated and the other isn't, the reader can't tell which is current. If
two docs need the same fact, one owns it and the other links. Generated docs (this catalog, the C4 set,
\`skill-catalog.md\`) are regenerated from source, never hand-edited, so they cannot drift.

### Content standards (beyond the frontmatter contract)
- **Lede first.** The \`>\` "when to use this document" blockquote is mandatory — it lets an agent decide
  whether to read on without loading the whole file.
- **Length is earned.** Link out to source (\`grounding\`) and to sibling docs instead of restating them.
  A foundation/reference doc past ~1–2 screens of prose is a smell — split it (by C4 level, repo map, or
  domain). "What's not in context doesn't exist" is not a licence to write everything down: record what an
  agent can't infer, link the rest.
- **One H1, strict hierarchy.** Exactly one \`#\` (the title), then \`##\` → \`###\` with no skipped levels
  and never a second H1.
- **Diagrams are Mermaid, fenced and guarded** (\`diagram-conventions\` + \`code-formatting\`); never a
  pasted screenshot for something that could be a diagram.

### Documentation as code
Docs are versioned in-repo, reviewed in the same PR as the change they describe, and validated by
\`doctor\` in CI (see \`documentation-as-code\`). A doc PR that fails \`doctor\` fails the build, exactly like
a failing test.
`,
  },
  {
    name: "spec-driven-development",
    title: "Spec-driven development",
    body: `# Spec-driven development

> Phase 1 seeded this standard. Phase 2 records this project's spec workflow in the \`{{PLACEHOLDER}}\` section.

A documented spec — acceptance criteria, expected behavior, edge conditions — comes **before** case design, automation, and code. This is the iron QA rule read from the authoring direction: the iron rule says every test traces *back* to an acceptance criterion; spec-driven development says that criterion must exist and be agreed *first*, so there is something to trace to. No spec ⇒ no cases ⇒ no automation. A test written before its criterion is recorded has nothing to anchor it — it ends up mirroring the implementation instead of the intended behavior.

## Rules
- **Spec precedes design.** Capture the acceptance criteria in \`context/changes/<id>/work.md\` (via \`qa-new\` / \`qa-ticket-review\`) before deriving cases. If the criteria are ambiguous or missing, that is a blocker to resolve — surface it, don't guess your way past it.
- **Cases derive from the spec, not the code.** Every case in \`cases.md\` names the criterion it covers. A case tracing to no criterion is either an undocumented requirement (write the spec) or scope creep (drop it).
- **Each criterion is testable when written.** "Works correctly" is not a criterion; "returns 429 when the rate limit is exceeded" is. \`qa-ticket-review\` marks each criterion testable / not-yet-testable; sharpen the not-yet-testable ones before design starts.
- **Spec changes ripple forward, in order:** update \`work.md\` first, then cases, then automation. Never patch a test to match new behavior while the criterion still describes the old behavior.
- This composes with \`grounding\` (cite the spec text a criterion derives from) and reinforces, never weakens, the iron QA rule.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the criterion is written and agreed first, then the case traces to it:
\`\`\`
work.md   AC-3.1 "API returns 429 once a client exceeds 100 requests/min"
cases.md  TC-12  "returns 429 when rate limit exceeded"  -> traces AC-3.1
test      limit.spec.ts implements TC-12
\`\`\`

❌ **Avoid** — a test written first, with the "spec" reverse-engineered from the code afterwards:
\`\`\`
test      "rate limit works"  (asserts whatever limiter.ts currently does)
work.md   (no acceptance criterion) -> nothing to trace to; mirrors the implementation
\`\`\`

## Applicable patterns

> Encouraged: the spec-first practices this project applies (Specification by Example,
> Given-When-Then acceptance criteria, BDD \`.feature\` files, ticket-as-spec) so agents follow the flow.

{{SPEC_DRIVEN_PATTERNS}}

## Project-specific spec workflow

> Record where this project's specs live and how they are agreed (ticket system, Confluence space, \`.feature\` files, the definition-of-ready) so agents read the spec before designing.

{{PROJECT_SPEC_WORKFLOW}}
`,
  },
  {
    name: "environment-management",
    title: "Environment & secrets management",
    body: `# Environment & secrets management

> Phase 1 seeded this standard. Phase 2 records this project's concrete environment matrix in the \`{{PLACEHOLDER}}\` section.

Tests run against more than one environment — a developer's local stack, CI, a shared staging deployment — and each needs its own base URL, test accounts, and data seeds. The configuration that points a run at an environment must live in **environment variables**, never as a secret committed to the repo. This is the same \`\${VAR}\` / \`\${env:VAR}\` indirection the \`atlassian\` and Playwright browser MCP servers already use for their credentials: the repo declares *which* variables a run needs; the values come from the environment (a local \`.env\` that is git-ignored, the CI secret store, a vault). "What's not in context doesn't exist" cuts both ways — a secret that *is* in context (committed) is a leak.

## Rules
- **Never commit a secret.** No passwords, API tokens, connection strings, or test-account credentials in the repo — not in code, not in config, not in \`context/\`. Reference them by env-var name (\`\${BASE_URL}\`, \`\${env:JIRA_API_TOKEN}\`) and keep the real value in a git-ignored \`.env\`, the CI secret store, or a vault. This is the same indirection the \`atlassian\` / browser MCP wiring uses.
- **One environment matrix, recorded once.** Maintain the local / CI / staging matrix in \`context/foundation/environments.md\`: per environment, its base URL(s), how to obtain a test account, and which data seed it expects. A run names its target environment; it does not hard-code the target's URL.
- **Base URL is configuration, not a literal.** Tests read the base URL from the environment (\`\${BASE_URL}\`), so the same suite runs anywhere. A URL pinned in a spec only works on the author's machine.
- **Test accounts and data seeds are per-environment and disposable.** Each environment has its own accounts and seed; never reuse a production account, and never assume staging data survives between runs. Record where each environment's seed comes from in \`environments.md\`.
- **CI is just another environment in the matrix.** Its variables come from the pipeline's secret store (wired by \`qa-ci-pipeline\`); the repo declares the names, the pipeline supplies the values.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the target is selected by environment, secrets come from the environment, nothing is committed:
\`\`\`
# .env (git-ignored) — values never committed
BASE_URL=https://staging.shop.example
TEST_USER=qa-bot@example.com
TEST_PASSWORD=…            # from the vault / CI secret store

# test reads configuration, not a literal
await page.goto(process.env.BASE_URL + "/checkout");   // runs on local, CI, staging
\`\`\`

❌ **Avoid** — environment pinned to one machine, a real secret committed to the repo:
\`\`\`
await page.goto("https://staging.shop.example/checkout");  // only works here
const token = "ghp_aJ9…live-token";                        // leaked secret in git history
\`\`\`

## Applicable patterns

> Encouraged: the environment patterns this project applies (\`.env\` + git-ignore, twelve-factor config,
> CI secret store, per-environment base-URL indirection, ephemeral/seeded test data) so agents follow them.

{{ENV_MGMT_PATTERNS}}

## Project-specific environment workflow

> Record this project's concrete matrix once known: each environment's base URL, how to get a test account, where its data seed comes from, and which secret store backs the env vars.

{{PROJECT_ENV_WORKFLOW}}
`,
  },
  {
    name: "test-data-management",
    title: "Test-data management",
    body: `# Test-data management

> Phase 1 seeded this standard. Phase 2 records this project's concrete data workflow in the \`{{PLACEHOLDER}}\` section.

The \`qa-test-data-gen\` factories/fixtures *produce* test data; this guideline governs its **lifecycle** — how data is kept fresh, isolated, seeded, cleaned up, and anonymized. A test that depends on data another test left behind, or on a row that happens to exist today, is not deterministic; it is a flake waiting to fire. Each test owns the data it needs: it sets that data up, and it tears it down, so the suite gives the same result on an empty database as on a full one, run alone or in parallel. This composes with \`environment-management\` (each environment has its own disposable seed) and reinforces the iron QA rule (a test you can't re-run cleanly is not evidence).

## Rules
- **Isolation between tests and runs.** A test never depends on data another test created or on order of execution. Create what you need inside the test (or its fixture); assume nothing about pre-existing rows. Two runs of the same suite, or two tests in parallel, must not collide — namespace data per test (unique ids/emails) so they can't.
- **Set up and tear down — clean up what you create.** Each test (or its fixture scope) is responsible for cleanup: delete created rows, reset mutated state, release seeded accounts. Prefer transactional rollback or an ephemeral/seeded database over hand-written deletes where the stack allows. Never leave residue that the next run must reason about.
- **Deterministic seeds.** When data is randomized (faker and friends), pin the seed so a failure reproduces; record the seed with the run. "Random but logged" beats "random and irreproducible". A fixed seed turns a heisenbug into a bug.
- **Freshness over staleness.** Don't rely on long-lived shared fixtures that drift from the schema; regenerate from the factories (which validate against the real contract) rather than maintaining a hand-edited dump. Stale seed data is the same hazard as a stale doc — "what's not regenerable rots".
- **No real PII — anonymize.** Never seed tests with real customer data. Use synthetic/faked values, or anonymized/masked extracts if production-shaped data is genuinely required. Real PII in a test fixture is the same leak class as a committed secret (see \`environment-management\`).

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the test seeds its own uniquely-named data and tears it down; nothing leaks between runs:
\`\`\`
test("locks the account after 5 failed logins", async () => {
  const user = await createUser({ email: uniqueEmail() }); // synthetic, per-test
  try {
    await failLogin(user, 5);
    await expect(login(user)).toBeRejectedWith("locked"); // AC-4.2
  } finally {
    await deleteUser(user); // cleanup — same result on a clean or full DB
  }
});
\`\`\`

❌ **Avoid** — depends on shared pre-existing data, leaves residue, and uses a real person:
\`\`\`
test("account locks", async () => {
  // assumes "jane.doe@gmail.com" (a real customer) already exists from another test
  await failLogin("jane.doe@gmail.com", 5);
  expect(isLocked).toBe(true);   // order-dependent; no cleanup; PII in the repo
});
\`\`\`

## Applicable patterns

> Encouraged: the data-lifecycle patterns this project applies (transactional rollback per test,
> ephemeral/containerized DB, fixture-scoped setup/teardown, seeded faker, data namespacing by test id)
> so agents follow them.

{{TEST_DATA_PATTERNS}}

## Project-specific data workflow

> Record this project's concrete lifecycle once known: how a test gets a clean slate, where seeds come from, the cleanup mechanism, the seed-logging convention, and the anonymization source for production-shaped data.

{{PROJECT_TEST_DATA_WORKFLOW}}
`,
    extended: `## Extended — factories, constants & migration

> Maintainer reference (generalized from the test-data-management source). The lean tier above is the
> deployed contract; this records the structural patterns that keep data DRY and maintainable.

### Centralize, then reuse
Test data lives in **one place per domain** (a factory / fixtures module / data class), not scattered as
inline literals across specs. A field that changes (a required header, a new mandatory property) is then a
one-line edit, not a find-and-replace across the suite. This is the structural complement to R-010's
factories: R-010 *produces* schema-valid objects; this governs *where they live and how they're named*.

### Factory / builder methods
- Name by **intent**: \`aValidCheckout()\`, \`anExpiredCard()\`, \`aUserWithoutPermission()\` — the call site
  reads as the scenario.
- Return a **builder** (or an object with overrides) so a test tweaks only the field it cares about and
  inherits valid defaults for the rest: \`aValidCheckout({ currency: "GBP" })\`.
- Boundary/invalid variants are **overrides on the valid base**, never a separate hand-maintained literal,
  so they stay in sync with the contract.

### Constants
Group fixed values by domain and name them in \`UPPER_SNAKE\`; never bury a magic literal in a test. A
shared constant is read once and reused, so a contract change updates every test through one edit.

### Environment-specific data
Each environment (local / CI / staging) owns its **own** seed and accounts (composes with
\`environment-management\`); a test names its target environment and reads the data for it, never
hard-coding a staging id. Per-test overrides layer on top of the environment defaults.

### Migration (hardcoded → managed)
When you find inline literals: (1) extract them to the domain factory/constants, (2) replace each literal
with a named reference, (3) parametrize the values that vary, (4) confirm the test still passes against a
clean database. Do it as a dedicated refactor, not buried in a behavior change.

### ✅ / ❌
- ✅ \`const user = await aUser({ email: uniqueEmail() }); try { … } finally { await deleteUser(user); }\`
- ❌ a literal \`"jane.doe@gmail.com"\` (real PII) reused across specs with no setup/teardown.
`,
  },
  {
    name: "performance-testing",
    title: "Performance testing",
    // (R-091) Conditional: only ships when a performance/load tool (JMeter) is in
    // the stack — the guideline is meaningless without one. Off a default scaffold.
    when: { performance: ["jmeter"] },
    body: `# Performance testing

> Phase 1 seeded this standard. Phase 2 records this project's concrete performance workflow in the \`{{PLACEHOLDER}}\` section.

Performance testing is the iron QA rule read from the **non-functional** side: a behavior's *speed and capacity* under load is verified the same way its *correctness* is — against a written target, with a result you actually observed. The \`qa-performance\` skill scripts and runs the load test (JMeter-first); this guideline governs *how* a performance test is designed so its numbers mean something. A load test with no defined budget, no baseline, or that asserts on averages is theater — it produces a graph nobody can pass or fail.

## Rules
- **NFRs before scripts.** Define the budget first: p95/p99 response time, throughput (req/s), max error-rate, and the concurrency to hold them at. "Fast enough" is not a target; "p95 < 300 ms at 200 concurrent users, error-rate < 1%" is. Every performance case traces to an NFR / acceptance criterion (composes with \`spec-driven-development\`); an undocumented target is a blocker, not a guess.
- **Percentiles, never averages.** Assert on p95/p99, not the mean — an average hides the slow tail that users actually feel. A run "passes" only when every percentile budget and the error-rate hold.
- **Record a baseline and compare.** Keep a baseline run to compare against so a regression is visible as a *delta*, not just an absolute number. "p95 rose from 180 ms to 240 ms since last release" is a finding; a lone "240 ms" is noise.
- **Realistic load shapes.** Model real usage: think-time between requests (no think-time overstates throughput), ramp-up, and parametrized/correlated data (CSV-driven, not one hard-coded user). Pick the profile deliberately — **load** (expected peak), **stress** (find the breaking point), **soak** (sustained, to catch leaks), **spike** (sudden surge).
- **Headless in CI, GUI only to author.** Runs are non-GUI (\`jmeter -n -t … -l …jtl -e -o …\`) so they are reproducible and CI-safe; the GUI is for building the plan, never for a measured run. A GUI run in CI is an anti-pattern (it can't even start without a display).

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a written budget, a percentile assertion against a baseline, headless run:
\`\`\`
NFR-2.1  "checkout p95 < 300 ms at 200 VUs, error-rate < 1%"
plan     checkout.jmx — 200-thread group, 1s think-time, CSV users, Duration Assertion @ 300ms
run      jmeter -n -t checkout.jmx -l results.jtl -e -o jmeter-report/
verdict  p95 = 268 ms (baseline 251 ms), errors 0.3% -> PASS, traces NFR-2.1
\`\`\`

❌ **Avoid** — no budget, average instead of percentile, GUI run, one hard-coded user:
\`\`\`
"ran the load test in the JMeter GUI, average response was ~250 ms, looks fine"
# no NFR to pass/fail, mean hides the p99 tail, not reproducible, single user ≠ load
\`\`\`

## Applicable patterns

> Encouraged: the performance practices this project applies (think-time timers, CSV Data Set Config,
> ramp-up profiles, a committed baseline, percentile SLAs as assertions) so agents follow them.

{{PERF_PATTERNS}}

## Project-specific performance workflow

> Record this project's concrete setup once known: the NFR source, where the baseline lives, the load profiles run, the environment load tests run against, and how the \`.jtl\`/dashboard are published.

{{PROJECT_PERF_WORKFLOW}}
`,
  },
  {
    name: "code-formatting",
    title: "Code & doc formatting",
    body: `# Code & doc formatting

> Phase 1 seeded this standard. Phase 2 records this project's concrete formatter setup in the \`{{PLACEHOLDER}}\` section.

Formatting is **deterministic and tool-owned**, never argued by hand. A configured autoformatter is the single source of truth for whitespace, line length, and import order; you run it, you don't reproduce it from memory or hand-tune to a personal style. This keeps review about behavior instead of style, and keeps diffs minimal — formatting churn buried in a logic change hides the change. The one exception is content the formatter would *mangle* — chiefly Mermaid diagrams (see \`diagram-conventions\`) — which is fenced off with \`@formatter:off\` / \`@formatter:on\` guards so the tool leaves it byte-stable.

- **Detected formatters / linters:** {{LINTERS}}

## Rules
- **The formatter is the source of truth.** Run the project's configured formatter/linter (\`{{LINTERS}}\`) before committing and let it decide whitespace, wrapping, and quoting. Don't hand-format to a different style and don't disable a rule to dodge a fix — fix the code. Once the formatter has run, style is not a review topic.
- **Format on save / pre-commit / in CI.** Wire the formatter to run automatically (editor on-save, a pre-commit hook, and a CI check that fails on a non-empty diff). A one-time "format the whole repo" commit pays the churn once; after that every change lands already-formatted, so each diff stays about behavior.
- **Deterministic import order.** Imports are grouped and ordered by the tool — a single canonical order (e.g. standard library → third-party → first-party → local, blank line between groups, side-effect/static imports last). Never hand-sort; let the formatter/linter enforce it so import blocks don't churn between authors.
- **Guard content the formatter would break.** Wrap anything whose exact layout is load-bearing — a Mermaid diagram, an aligned table, ASCII art, a deliberately ordered literal — in formatter-off guards so reflowing/reordering can't corrupt it. In Markdown use the HTML-comment form \`<!-- @formatter:off -->\` … \`<!-- @formatter:on -->\`; in code use the language's line-comment form (\`// @formatter:off\`, \`# fmt: off\`). Always pair an \`off\` with an \`on\` — an unclosed guard silently disables formatting for the rest of the file.
- **Guards are a scalpel, not a blanket.** Disable formatting for the smallest region that needs it; never wrap a whole file to avoid running the formatter. This composes with \`diagram-conventions\`: every rendered Mermaid block in \`context/\` and in reports carries the guard so it survives an autoformat pass — diagrams are born compliant.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the diagram is fenced off so the formatter can't reflow it, and imports are left to the tool:
\`\`\`\`markdown
<!-- @formatter:off -->
\`\`\`mermaid
flowchart LR
  ac[Acceptance criterion] --> tc[Test case] --> at[Automated test]
\`\`\`
<!-- @formatter:on -->
\`\`\`\`

❌ **Avoid** — an un-guarded diagram (the next autoformat realigns the arrows and breaks the render) and hand-sorted imports that churn on every PR:
\`\`\`\`
\`\`\`mermaid
flowchart LR
  ac[Acceptance criterion]-->tc[Test case]
\`\`\`
import { z } from "zod"; import { local } from "./local"; import { http } from "axios"; // hand-ordered, no grouping
\`\`\`\`

## Applicable patterns

> Encouraged: name the formatting tools/configs this project standardizes on
> (Prettier + ESLint, Spotless + google-java-format, Black + ruff/isort, EditorConfig,
> a pre-commit framework) so agents run the right one.

{{FORMATTER_PATTERNS}}

## Project-specific formatting workflow

> Record this project's concrete setup once known: the formatter command, where its config lives, the pre-commit / CI hook that enforces it, and any standing \`@formatter:off\` regions.

{{PROJECT_FORMATTING_WORKFLOW}}
`,
  },
  {
    name: "mcp-content-fetch",
    title: "MCP content fetch",
    // (R-091) Conditional: only ships when a ticket/spec/attachment fetch MCP is
    // enabled (the local Atlassian server, Xray, or markitdown) — there is nothing
    // to fetch through MCP otherwise. Off a default scaffold (all MCP opt-ins off).
    when: { mcp: ["atlassian", "xray", "markitdown"] },
    body: `# MCP content fetch

> Phase 1 seeded this standard. Phase 2 records this project's concrete fetch sources in the \`{{PLACEHOLDER}}\` section.

When a ticket, spec, test issue, or attachment is the input to a refinement, bug report, or plan, you **fetch it through MCP and read it** — you do not summarize from memory or from the ticket title. Skipping a step here (summarizing before the attachment is downloaded, converting a URL instead of a local file, guessing at a binary's contents) is the **#1 cause of hallucinated summaries**. The ordering below is a guarantee, not a suggestion: download → verify → convert → read, in that order, every time. "What's not in context doesn't exist" — an attachment you have not converted and read is not evidence.

## The fetch flow (in order)
1. **Discover.** \`getIssue\` for the Jira key → if it is a test issue (Test / Test Execution / Test Plan / Test Set), use the **\`xray\`** server → follow links to Confluence (\`getPage\` / \`searchConfluence\`) → list attachments (\`getAttachments\`) → fetch each (\`getAttachmentContent\`).
2. **Download to a staging path.** Save every attachment under \`context/refinements/.attachments/<source-id>/<filename>\`, where \`<source-id>\` is the \`JIRA-KEY\` | \`PAGE-ID\` | \`XRAY-KEY\` it came from. Stage by source so two tickets can't collide.
3. **Pre-flight verify.** Before converting, confirm the file **exists and its size is > 0**. A zero-byte or missing download is a failure to surface, not a file to summarize.
4. **Convert on the local path only.** Run **\`markitdown\`** against the **local file path** — never a URL or an attachment id (markitdown is local-path only). Read text formats (\`.md\` / \`.txt\` / \`.json\`) directly; use \`view_image\` for images. Only the converted Markdown is evidence you may cite.
5. **Clean up.** Remove the staging dir when done — it is git-ignored scratch, never committed.

## Source priority
Prefer the most authoritative source: **Jira + Xray** (for test issues) > **Jira** > **Confluence** > **Attachments**. Reach for an attachment only when the structured sources don't carry the fact.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — download, verify, then convert the local file, and cite the converted text:
\`\`\`
getAttachmentContent PROJ-217 spec.docx
  -> context/refinements/.attachments/PROJ-217/spec.docx   (12 KB, exists)
markitdown context/refinements/.attachments/PROJ-217/spec.docx
  -> "AC-2: reject empty cart at checkout"   (cited from the converted Markdown)
\`\`\`

❌ **Avoid** — summarizing from the title, or converting a URL instead of the verified local file:
\`\`\`
"The spec.docx probably covers the checkout flow."   # never downloaded/read — a guess
markitdown https://jira/secure/attachment/9001/spec.docx   # markitdown is local-path only
\`\`\`

## Applicable patterns

> Encouraged: the fetch practices this project relies on (source-id staging dirs, download→verify→convert
> ordering, Xray-first for test issues, git-ignored \`.attachments/\`) so agents follow them.

{{MCP_FETCH_PATTERNS}}

## Project-specific fetch sources

> Record this project's concrete sources once known: the Jira/Confluence/Xray hosts, the doc space(s) specs live in, and which attachment formats actually appear.

{{PROJECT_MCP_FETCH_WORKFLOW}}
`,
  },
  {
    name: "multi-repo-boundaries",
    title: "Multi-repo workspace boundaries",
    // (R-091) Conditional: only ships in a multi-repo workspace (a `workspace`
    // block exists). Inert — and absent — on a single-repo scaffold.
    when: { multiRepo: true },
    body: `# Multi-repo workspace boundaries

> Phase 1 seeded this standard. Phase 2 records this workspace's concrete repo topology in the \`{{PLACEHOLDER}}\` section.

This orchestration can run over a **parent folder holding several repositories**: one **test repo** — the repo that carries the test framework, where *all* orchestration artifacts (this \`context/\` system of record, the skills/prompts, the MCP config, the manifest) live — and one or more **developer repos** holding the application source. The boundary is absolute: **the test repo is the only writable area; the developer repos are read-only source.** Skills read application code at \`../<repo>/file:line\` to plan, design, and ground tests, but they **never create, edit, or delete a file in a developer repo** — those repos belong to the product teams, and a stray test artifact in one is a leak, the same class of mistake as a committed secret. On a single-repo workspace this guideline is inert (there are no developer repos), and everything behaves as it always has.

## Rules
- **One writable root.** Every file the tool or its agents write lands inside the test repo. If a task seems to need a change in a developer repo (a fixture, a test hook, a build tweak), that is a request to the owning team — raise it, don't make it.
- **Developer repos are read-only source.** Read them to understand the system and to ground claims (\`../<repo>/src/...#Lnn\`), exactly as you read the test repo's own source. Reference them as **inline-code relative paths** (\`../<repo>/\`), never as Markdown links, so the reference can't rot into a broken-link error.
- **Resolve source across the workspace.** A developer repo sits at \`../<repo>/\` relative to the test repo. The dev-repo list lives in \`context/foundation/repo-map.md\` ("External source repositories") and the manifest's \`workspace\` block — read it to know which repos are in scope.
- **The editor enforces it too.** The generated \`.code-workspace\` pins the developer-repo folders read-only (\`files.readonlyInclude\`), and \`doctor\` fails the build if any scaffold output leaks into a developer-repo tree. Persuasion (this rule), a native guardrail (the editor), and an out-of-loop check (\`doctor\`) reinforce each other — none is a substitute for keeping the boundary in mind.

## Embedded test topology (the test framework lives *inside* a developer repo)

A third layout: the test framework has **no repo of its own** — it lives as a **subtree** of a developer repo (an \`e2e/\` folder, or a build module such as a Maven submodule / Gradle subproject / workspace package). The writable area is then a *subtree* of a repo that is otherwise application source. The manifest records it as a \`testSubpath\` inside the host repo (\`testRepo\`, or \`"."\` for a single host repo with no siblings).

- **The writable area is the test subtree plus the host-root config.** Everything the tool or its agents write lands inside \`{testSubpath}/\` (new tests, page objects, fixtures, test data) or the orchestration config at the host root (\`context/\`, the platform config, the manifest). Nothing else.
- **The rest of the host repo is read-only application source.** Read it at \`file:line\` to plan and ground tests — never create, edit, or delete a file outside \`{testSubpath}/\`. A stray test artifact in the host's \`src/\` is a leak, the same class of mistake as writing into a developer repo.
- **Sibling developer repos stay read-only** (multi-host), exactly as above — read at \`../<repo>/file:line\`, never written.
- **The editor enforces it too.** Single-host writes \`files.readonlyInclude\` (host source) + \`files.readonlyExclude\` (\`{testSubpath}/\` + config) into \`.vscode/settings.json\`; multi-host adds a \`readonlyExclude\` carve-out to the \`.code-workspace\`. \`doctor\` fails the build on any write outside the writable set.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — read application source from the dev repo, write the test + docs into the test repo:
\`\`\`
read   ../payments-api/src/checkout/Limiter.java#L40-L58   (ground the AC)
write  tests/checkout/rate-limit.spec.ts                   (test, in the test repo)
write  context/changes/checkout-rate-limit/cases.md        (doc, in the test repo)
\`\`\`

❌ **Avoid** — writing into a developer repo (a leak; not ours to change):
\`\`\`
write  ../payments-api/src/test/FixtureHack.java   # editing read-only source
write  ../payments-api/.claude/skills/...          # scaffolding into a dev repo
\`\`\`

✅ **Good (embedded, \`testSubpath: e2e\`)** — read host source, write only into the test subtree + config:
\`\`\`
read   src/checkout/limiter.ts#L40-L58        (ground the AC — host application source)
write  e2e/checkout/rate-limit.spec.ts        (test, inside the writable subtree)
write  context/changes/checkout-rate-limit/cases.md   (doc, host-root config)
\`\`\`

❌ **Avoid (embedded)** — writing into host application source outside the subtree:
\`\`\`
write  src/checkout/limiter.ts        # editing read-only host source
write  package.json                   # touching a host-root file that isn't orchestration config
\`\`\`

## Applicable patterns

> Encouraged: the workspace patterns this team uses (a parent \`.code-workspace\`, a dedicated test repo per
> product, \`files.readonlyInclude\` pins, cross-repo \`../<repo>/\` source references) so agents follow them.

{{MULTI_REPO_PATTERNS}}

## Project-specific workspace topology

> Record this workspace's concrete topology once known: which repo is the test repo, the developer repos in
> scope and what each owns, and how source is shared (relative paths, the \`.code-workspace\`).

{{PROJECT_MULTI_REPO_WORKFLOW}}
`,
    extended: `## Extended — repo scope & exclusions

> Maintainer reference (generalized from the excluded-repos source). The lean tier above is the deployed
> contract (the write boundary). This records how to decide which repos are even *in scope to read*.

### Three scope tiers
- **In scope (read freely)** — the developer repos chosen at \`init\`, holding the application source under
  test. Read them at \`../<repo>/file:line\` to plan and ground tests.
- **Hard exclusions (never read or cite)** — third-party tooling not owned by the team, contract-test repos
  with separate ownership/lifecycle, and the test repo *itself* when it would be mis-attributed as the
  system under test. Do **not** read their source for factual claims, cite their files in analysis/RCA/
  refinement output, draw their classes in diagrams, or recommend changes to them. If a ticket references
  one, mark \`[Out of scope: <repo>]\` and ask the user how to proceed.
- **Soft exclusions (avoid unless asked)** — archived repos (read-only historical context) and build-output
  directories (\`*-target/\`, \`dist/\`, \`build/\` — never a source of truth).

### Self-reference discipline
When documenting a *tested service*, the owning component is the **service**, never the test repo — the
test class that found a bug is referenced as "detected by \`<TestClass>\` in the test repo", which is
documentation, not scope inclusion. Only when the work is *about the test framework itself* is the test
repo the analysis target.

### Why this composes with the write boundary
The lean tier forbids *writing* to dev repos; this tier narrows what you even *read*. Together they keep
analysis grounded in the right sources (no third-party noise, no build artifacts) and keep every generated
artifact inside the one writable test repo. When in doubt about a repo's tier, ask the user — guessing
scope is the same class of error as guessing a fact (\`grounding\`).

### ✅ / ❌
- ✅ ground an AC in \`../payments-api/src/checkout/Limiter.java#L40-L58\`; mark a ticket touching a
  third-party repo \`[Out of scope: reportportal]\` and ask.
- ❌ cite \`../some-vendor-fork/...\` in an analysis, or treat \`../app/target/...\` build output as the spec.
`,
  },
  {
    name: "security-testing",
    title: "Security testing",
    // (R-093) Conditional: ships only when a security/DAST tool (e.g. ZAP) is in
    // the stack — a forward-looking `when` (no detector populates `stack.security`
    // until the qa-security skill, R-055). Until then it deploys only via the R-092
    // wizard override. The rich review/SAST `extended` tier is deferred to R-055.
    when: { security: ["zap"] },
    body: `# Security testing

> Phase 1 seeded this standard. Phase 2 records this project's concrete security workflow in the \`{{PLACEHOLDER}}\` section.

Security testing is the iron QA rule read from the **security** side: a behavior's resistance to misuse is
verified the same way its correctness is — against a written requirement, with a result you actually
observed. Every security case traces to a **security requirement / acceptance criterion** (composes with
\`spec-driven-development\`); a scan with no requirement to pass or fail is noise, not a test. The
\`qa-security\` skill runs the tooling (DAST-first, OWASP ZAP); this guideline governs *how* a security
test is designed so its findings mean something.

## Rules
- **A threat model is the input.** Before scanning, state what you are protecting and against whom (the
  assets, the entry points, the trust boundaries). The threat model is the spec security cases trace to —
  "scan the app" is not a target; "an unauthenticated user must not read another tenant's orders" is.
- **OWASP Top-10 / ASVS as the baseline.** Map every finding to a recognized identifier (OWASP Top-10
  category, CWE, ASVS requirement) so it is triageable and traceable, not just a scanner line.
- **Shift left.** Dependency scanning and static checks run early (in the loop / pre-merge); DAST runs
  against a deployed environment. Catch what you can before deploy; verify the rest against the running app.
- **Record a vulnerability baseline and triage against it.** Keep a baseline of known/accepted findings so
  a new run surfaces *new* issues as a delta — a known, risk-accepted item must not re-fail the gate, and a
  new Critical must not hide in the noise. Triage by severity (CVSS / OWASP severity), never by raw scanner
  count: ten Lows are not one Critical.
- **Headless & CI-safe; secrets out of scan config.** Run scans non-interactively so they are reproducible
  in CI (the GUI is only for authoring a scan profile). Scan configuration flows credentials through
  environment variables (see \`environment-management\`) — never a token committed in a \`.zap\` / scan file.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a requirement-anchored finding, mapped to a standard, triaged against a baseline:
\`\`\`
SR-1.2  "an unauthenticated request to /orders/{id} must return 401, never order data"
scan    ZAP baseline (headless) against staging, auth via \${ZAP_AUTH_TOKEN}
finding A01:2021 Broken Access Control (CWE-862) — /orders/42 returns 200 unauthenticated
verdict NEW vs baseline, Critical -> fails the gate, traces SR-1.2
\`\`\`

❌ **Avoid** — no requirement, raw counts, a clean baseline read as "secure", a committed secret:
\`\`\`
"ran ZAP, 0 alerts on the login page, so the app is secure"   # no threat model, partial scope
# .zap config with ZAP_AUTH_TOKEN="ghp_live…" committed to the repo (leaked secret)
\`\`\`

## Applicable patterns

> Encouraged: the security-testing practices this project applies (DAST baseline vs full scan, dependency
> scanning in CI, a committed vulnerability baseline, OWASP/CWE mapping on findings, severity-gated
> pipelines) so agents follow them.

{{SECURITY_PATTERNS}}

## Project-specific security workflow

> Record this project's concrete setup once known: the threat-model source, the DAST tool + scan profiles,
> where the vulnerability baseline lives, the severity gate, and which secret store backs the scan env vars.

{{PROJECT_SECURITY_WORKFLOW}}
`,
  },
];

/** The `context/` system of record laid down at scaffold time. */
export const FOUNDATION: Array<{ rel: string; body: string }> = [
  {
    rel: "context/foundation/test-strategy.md",
    body: `---
title: Test strategy
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-init
status: seeded
---
# Test strategy

> Durable. Filled by \`qa-init\` in phase 2. Keep lean; link out, don't duplicate.

- **Product under test:** {{PRODUCT_UNDER_TEST}}
- **Critical user journeys:** {{CRITICAL_JOURNEYS}}
- **Risk priorities:** {{RISK_PRIORITIES}}
- **Out of scope:** {{OUT_OF_SCOPE}}
`,
  },
  {
    rel: "context/foundation/test-plan.md",
    body: `---
title: Test plan
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-test-plan
status: seeded
---
# Test plan

> Durable. Owned by the \`test-plan\` skill.

- **Scope:** {{TEST_PLAN_SCOPE}}
- **Test levels & split:** {{TEST_LEVELS}}
- **Entry / exit criteria:** {{ENTRY_EXIT_CRITERIA}}
- **Tooling:** {{AUTOMATION_FRAMEWORK}}
- **Reporting cadence:** {{REPORTING_CADENCE}}
`,
  },
  {
    rel: "context/foundation/environments.md",
    body: `---
title: Environments
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-init
status: seeded
---
# Environments

> Durable. How to reach each test environment. "What's not in context doesn't exist."

- **Environments:** {{ENVIRONMENTS}}
- **Base URLs / endpoints:** {{BASE_URLS}}
- **Auth / credentials handling:** {{AUTH_HANDLING}}
- **Test data sources:** {{TEST_DATA_SOURCES}}
`,
  },
  {
    rel: "context/foundation/tools.md",
    body: `---
title: Tools & result artifacts
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-automation-bootstrapper
status: seeded
---
# Tools & result artifacts

> Durable. Records where test results live so skills can read outcomes directly.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Run command:** {{RUN_COMMAND}}
- **Report path:** {{REPORT_PATH}}
- **Trace / screenshot path:** {{TRACE_PATH}}
- **Machine-readable results (e.g. JUnit XML):** {{RESULTS_PATH}}
`,
  },
  {
    rel: "context/foundation/test-framework.md",
    body: `---
title: Test framework
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-automation-bootstrapper
status: seeded
---
# Test framework

> Durable. How the automation framework is organized and how to work in it.
> Owned by qa-automation-bootstrapper; enriched in phase 2.
> Machine-read result paths live in tools.md — don't duplicate them here.
> Reads: qa-conventions, test-naming, code-formatting, environment-management.

## Stack
- **Framework:** {{AUTOMATION_FRAMEWORK}} · **Build tool:** {{BUILD_TOOL}} · **Language:** {{PROJECT_LANGUAGE}}
- **Key libraries / versions:** {{KEY_LIBRARIES}}

## Project test layout
<where tests live; directory structure; naming — cross-links context/foundation/repo-map.md>

## How to run
| Mode | Command |
|------|---------|
| All tests | {{RUN_COMMAND}} |
| Single test / file | {{RUN_SINGLE}} |
| By tag / group | {{RUN_TAGGED}} |
| Headed / debug / UI | {{RUN_DEBUG}} |
| Update snapshots / baselines | {{RUN_UPDATE}} |

## Conventions
- **Base test class / fixtures:** <setup/teardown entry points>
- **Page objects / request builders / clients:** <the abstraction tests use>
- **Tags / categories:** <how tests are grouped>
- **Naming:** see the test-naming guideline

## Authentication & environment setup
<how tests authenticate; required env vars — see environments.md + environment-management>

## How to add a new test
1. <framework-specific step-by-step walkthrough>

## Reference example tests
- \`<path>\` — <which pattern it demonstrates>

## CI integration
<pointer to the qa-ci-pipeline workflow that runs this framework>
`,
  },
  {
    rel: "context/foundation/framework-architecture.md",
    body: `---
title: Framework architecture (P3)
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-framework-analyze
status: seeded
---
# Framework architecture (P3)

> Durable. The **generated structural map** of the test-automation framework — base
> classes, fixtures, page objects/clients, config, and extension points — produced by
> \`qa-framework-analyze\` (phase 2) from the framework code, grounded at \`file:line\`. This
> is pillar **P3**: \`qa-test-automate\` reads it so authored test code matches the framework
> *as documented*, not as guessed. Distinct from \`test-framework.md\` (the hand-authored
> how-to-run onboarding guide); re-run as the framework evolves. Paths are inline code, not
> links (\`grounding\` — confirm each before relying on it).

## Architecture diagram
> One guarded Mermaid diagram (component / flowchart per \`diagram-conventions\`) of the
> framework's building blocks and how a test flows through them.

{{FRAMEWORK_ARCH_DIAGRAM}}

## Base classes & test lifecycle
> The base test class(es) and setup/teardown hooks every test inherits, each at its source.

{{FRAMEWORK_BASE_CLASSES}}

## Fixtures & dependency wiring
> Shared fixtures / dependency injection (Playwright fixtures, pytest fixtures, JUnit
> extensions, Spring test context) and what each provides.

{{FRAMEWORK_FIXTURES}}

## Page objects / request builders / clients
> The abstractions tests drive the system through, and where to add a new one.

{{FRAMEWORK_ABSTRACTIONS}}

## Configuration & environment wiring
> How config / env reaches a test (see \`environments.md\`, \`environment-management\`) — base
> URLs, profiles, secrets indirection — at its source.

{{FRAMEWORK_CONFIG}}

## Extension points
> Where and how to extend the framework (a new fixture, client, custom matcher, reporter
> hook) without breaking existing tests.

{{FRAMEWORK_EXTENSION_POINTS}}
`,
  },
  {
    rel: "context/foundation/lessons.md",
    body: `---
title: Lessons & golden rules
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-archive
status: seeded
---
# Lessons & golden rules

> Append-only playbook. \`qa-archive\` adds reusable lessons here so future runs
> don't repeat mistakes (flaky areas, data tricks, tooling gotchas).

{{LESSONS}}
`,
  },
  {
    rel: "context/foundation/tech-debt-tracker.md",
    body: `---
title: Tech-debt tracker
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-archive
status: seeded
---
# Tech-debt tracker

> Durable, append-only — a first-class, versioned backlog of test debt and
> known-flaky areas. \`qa-archive\` appends entries as work-items close. Nothing
> here is auto-deleted: an item is resolved by linking the work-item that paid it
> down, not by removing the row, so the history of what we owed survives.

## Open test debt

> Each entry: id, area, what's owed, severity, and the work-item that found/introduced it.

{{TECH_DEBT}}

## Known flaky areas

> Tests or areas that fail intermittently — the quarantine reason and a link to the tracking work-item.

{{FLAKY_AREAS}}
`,
  },
  {
    rel: "context/foundation/repo-map.md",
    body: `---
title: Repo map — test surface ↔ source
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-reverse-engineer
status: seeded
---
# Repo map — test surface ↔ source

> Durable navigation aid for large / multi-module / polyglot repos: find the right
> place fast instead of blind-searching. **Two-phase.** Phase 1 wrote the
> deterministic **path inventory** below (build roots, test directories, test/CI
> configs) by scanning the repo — always fresh, no LLM. Phase 2
> (\`qa-reverse-engineer\`) enriches the test↔source map and entry points, reusing the
> C4 L2/L3 container/component names from \`context/reference/\` (see the
> \`diagram-conventions\` guideline). Paths are shown as inline code, not links, so
> this file never breaks the \`doctor\` link check; confirm each before relying on it
> (\`grounding\`).

## Path inventory (phase 1 — auto-generated, no LLM)

{{REPO_MAP_INVENTORY}}

{{DEVELOPER_REPOS}}## Test ↔ source map (phase 2)

> For each test directory above, the application module / C4 container it exercises
> and where that source lives. Reuse the container/component names from
> \`context/reference/\` so the two maps agree.

{{REPO_MAP_TEST_SOURCE_LINKS}}

## Entry points (phase 2)

> The ways into the system tests target — HTTP routes, CLI, scheduled jobs, message
> consumers — each linked to the test directory that covers it, or flagged uncovered.

{{REPO_MAP_ENTRY_POINTS}}
`,
  },
  {
    rel: "context/reference/system-overview.md",
    body: `---
title: System reference — C4 index
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-reverse-engineer
status: seeded
---
# System reference — C4 index

> Durable. Produced by \`qa-reverse-engineer\` in phase 2 from the application source, following the
> **C4 model** (L1 Context → L2 Container → L3 Component → L4 Code) rendered with Mermaid — see the
> \`diagram-conventions\` guideline. For a large/monolith codebase the skill first proposes how to split
> this, then fills it. Links out to real source paths — it does not duplicate code.

{{DEVELOPER_REPOS}}## Architecture (C4)
- **L1 — System context:** [c4-context.md](./c4-context.md)
- **L2 — Containers:** [c4-container.md](./c4-container.md)
- **L3 — Components:** [c4-component.md](./c4-component.md)
- *L4 — Code:* generated on demand for a specific component; not kept as a standing doc (link to source).

## Business context
> What the system is for, who uses it, and the value it delivers.

{{BUSINESS_CONTEXT}}

## Test surface (QA lens)
> The testing view over the architecture (C4 above is the architecture layer). What is risky, what is
> untested, and where the integration seams are. All claims verified at \`file:line\` (grounding);
> inferences live in the Assumptions table only.

### Integration points
> The map for integration-test planning: every system this one talks to.

| Integrated system | Repo / module | Integration point | Direction | Protocol | Data exchanged | Test focus |
|-------------------|---------------|-------------------|-----------|----------|----------------|------------|

### Entry-point inventory
> Every way into the system tests target, each tied to its source and coverage status.

| Entry point | Type | Source (file:line) | Covered by tests? |
|-------------|------|--------------------|-------------------|
| <METHOD /path · CLI · job · consumer> | HTTP / CLI / job / event | <path#Lnn> | yes / no / partial |

### API / endpoint inventory
> Every callable API surface with the contract detail case design needs (richer than the
> coverage-focused entry-point inventory above): method, path, auth, request/response shape,
> and status codes — each grounded at \`file:line\` (R-074).

| Method · path | Auth | Request (key fields) | Responses (status codes) | Source (file:line) |
|---------------|------|----------------------|--------------------------|--------------------|
| <GET /things/{id}> | <scheme / none> | <key request fields> | <200 / 400 / 404 / …> | <path#Lnn> |

### Data model & boundaries
> The fields/entities under test, with their valid and invalid/boundary values for case design.

| Field / entity | Type | Valid | Invalid / boundary | Source (file:line) |
|----------------|------|-------|--------------------|--------------------|

### Test scenarios summary
- <high-level positive / negative / integration scenarios; link to cases.md when designed>

### Questions & issues
| ID | Question / uncertainty | Impact | Status |
|----|------------------------|--------|--------|

### Completeness verification
> Self-check before this reference is trusted (R-074): confirm the inventories are exhaustive
> and grounded. Per the \`documentation\` standard, this is part of earning the doc's length —
> an inventory that silently drops an endpoint is worse than one that flags the gap.

- [ ] Every entry point / endpoint discoverable in the source is listed above — none silently dropped.
- [ ] Every inventory row cites a real \`file:line\` (\`grounding\`); nothing inferred sits outside the **Assumptions** table.
- [ ] Every integration point has a direction, protocol, and test focus.
- [ ] Gaps and uncertainties are recorded in **Questions & issues** / **Assumptions**, not omitted.
`,
  },
  {
    rel: "context/reference/c4-context.md",
    body: `---
title: C4 L1 — System context
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-reverse-engineer
status: seeded
---
# C4 L1 — System context

> Durable. Filled by \`qa-reverse-engineer\` (phase 2). One \`C4Context\` (or \`flowchart\` fallback) Mermaid
> diagram per the \`diagram-conventions\` guideline: the system as one box, its users, and the external
> systems it talks to. Confirm every integration in the source before drawing it (\`grounding\`).

{{C4_CONTEXT_DIAGRAM}}

## Users & external systems
> Each actor / external system, what it exchanges with the system, and the integration point in the code.

{{C4_CONTEXT_NOTES}}
`,
  },
  {
    rel: "context/reference/c4-container.md",
    body: `---
title: C4 L2 — Containers
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-reverse-engineer
status: seeded
---
# C4 L2 — Containers

> Durable. Filled by \`qa-reverse-engineer\` (phase 2). A \`C4Container\` (fallback: \`flowchart\`) diagram of
> the deployable/runnable units inside the system boundary (apps, services, data stores, queues) and how
> they communicate. Link each container to its source root.

{{C4_CONTAINER_DIAGRAM}}

## Containers & data flow
> Each container: responsibility, technology, source root, and the data that flows in and out.

{{C4_CONTAINER_NOTES}}
`,
  },
  {
    rel: "context/reference/c4-component.md",
    body: `---
title: C4 L3 — Components
version: 0.1.0
last-updated: {{LAST_UPDATED}}
owner-skill: qa-reverse-engineer
status: seeded
---
# C4 L3 — Components

> Durable. Filled by \`qa-reverse-engineer\` (phase 2), zooming into the testing-critical container(s). A
> \`C4Component\` (fallback: \`flowchart\`) diagram of the components inside a container plus the entry
> points (HTTP routes, CLI, jobs, consumers) that exercise them. Skip L4 (code) unless a component needs it.

{{C4_COMPONENT_DIAGRAM}}

## Components & entry points
> Each component: responsibility, key source paths, and the entry point(s) that reach it.

{{C4_COMPONENT_NOTES}}
`,
  },
  {
    rel: "context/changes/.gitkeep",
    body: "",
  },
  {
    rel: "context/archive/.gitkeep",
    body: "",
  },
  {
    rel: "context/refinements/.gitkeep",
    body: "",
  },
  {
    rel: "context/knowledge/.gitkeep",
    body: "",
  },
];
