import type { LogicalSkill } from "./skills.js";

/**
 * Platform-agnostic content for the lean root config, the guideline docs, and the
 * `context/` system of record. All strings may carry `{{PLACEHOLDER}}` markers —
 * the scaffold orchestrator renders phase-1 vars and leaves the rest for phase 2.
 */

const BUCKET_TITLE: Record<LogicalSkill["bucket"], string> = {
  backbone: "Backbone — process & context",
  design: "Test design",
  automation: "Automation",
  analysis: "Analysis & data",
};

/**
 * The lean root "map" (~table of contents, not an encyclopedia). `invoke` is how
 * this platform refers to running a skill (e.g. "skill" vs "prompt").
 */
export function rootConfigMarkdown(skills: LogicalSkill[], invoke: string): string {
  const buckets: LogicalSkill["bucket"][] = ["backbone", "design", "automation", "analysis"];
  const skillList = buckets
    .map((b) => {
      const rows = skills
        .filter((s) => s.bucket === b)
        .map((s) => `- \`${s.name}\`${s.readOnly ? " *(read-only)*" : ""} — ${s.description}`)
        .join("\n");
      return `### ${BUCKET_TITLE[b]}\n${rows}`;
    })
    .join("\n\n");

  return `# QA orchestration — root map

> Lean index, not a manual. Knowledge lives in \`context/\`; pull it just-in-time.
> Generated by the QA-process scaffolder (phase 1). \`{{PLACEHOLDER}}\` markers are
> completed in phase 2 by the in-tool LLM. Keep this file short.

- **Stack:** {{PROJECT_LANGUAGE}} / {{BUILD_TOOL}}
- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Report language:** {{REPORT_LANGUAGE_NAME}}
- **Agent autonomy:** {{AUTONOMY_LEVEL}}
- **Generated:** {{GENERATED_AT}}

## Iron QA rule (non-negotiable — survives compaction)

> Every behavior under test ships with automated tests in **{{AUTOMATION_FRAMEWORK}}**.
> Every test case traces to an acceptance criterion. New behavior ⇒ new tests;
> changed behavior ⇒ updated tests. Work without passing tests is not done.

## Grounding rule (non-negotiable — survives compaction)

> Ground every claim in a real, checkable artifact — cite \`file:line\`, a ticket
> id, or result-MCP output. Never invent files, paths, APIs, schemas, or test
> results; if you cannot cite it, say so and flag the uncertainty. A "passing"
> test you didn't observe pass is not evidence. What's not in context doesn't
> exist. See the \`grounding\` guideline.

## Read before you write (standing rule)

> Before any **write** skill changes a file, read the guidelines/standards that
> bear on the task — at minimum \`qa-conventions\` and \`test-naming\`, plus any that
> apply (\`spec-driven-development\`, \`grounding\`, \`documentation-as-code\`,
> \`diagram-conventions\`). Don't act from memory: the standards live in the
> guideline files; pull them in first so the work conforms by construction
> instead of being corrected after. Composes with the grounding rule (read, don't
> recall) and documentation-as-code.

## How to work

1. Open or create a work-item with \`qa-new\` (id = \`<stream>-<slug>\`, stable).
2. Drive it: \`qa-ticket-review\` → \`qa-test-plan\`/\`qa-test-case-design\` → \`qa-automation-bootstrapper\`/\`qa-test-automate\` → run → \`qa-rca\` on failure → \`qa-review\` → \`qa-archive\`.
3. Run each step as a ${invoke}. State of record lives under \`context/\` — read it before acting, update it after.

## Skills

${skillList}

## Where things live

- \`context/foundation/\` — durable: test strategy, test plan, environments, tools, lessons, tech-debt tracker.
- \`context/changes/<work-id>/\` — in-flight work (work.md, plan.md, cases.md, automation.md).
- \`context/archive/<work-id>/\` — completed work (read-only history).
- \`context/reference/\` — reverse-engineered system docs (produced by \`qa-reverse-engineer\`).
- Guidelines — QA conventions & naming (see the guidelines files).
`;
}

/** Guideline documents (same content both platforms; only the path differs). */
export const GUIDELINES: Array<{ name: string; title: string; body: string }> = [
  {
    name: "qa-conventions",
    title: "QA conventions",
    body: `# QA conventions

> Phase 1 seeded this from the wizard. Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Static checks:** {{LINTERS}}

## Rules

{{QA_CONVENTIONS}}

## Test quality (non-negotiable)

- One behavior per test; deterministic, independent, parallel-safe — no sleeps.
- Cover negative and boundary cases, not just the happy path.
- Assert intended behavior, not a mirror of the implementation.
- Capture diagnostics on failure (trace/screenshot/log) at the paths recorded in \`context/foundation/tools.md\`.

## Project-specific conventions

> Record only non-obvious, project-specific rules an agent would otherwise get wrong.

{{PROJECT_SPECIFIC_CONVENTIONS}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it. Keep these short and real to this codebase.

✅ **Good** — one behavior, deterministic, waits on a condition, traces to an AC:
\`\`\`
test("returns 429 when the rate limit is exceeded", async () => {
  await sendRequests(limit + 1);
  await expect(lastResponse).toHaveStatus(429); // AC-3.1
});
\`\`\`

❌ **Avoid** — two behaviors, a fixed sleep, order-dependent state:
\`\`\`
test("rate limit", async () => {
  await sleep(2000);          // flaky: races the limiter
  expect(res.status).toBe(429);
  expect(user.isLoggedIn);    // unrelated second assertion
});
\`\`\`

## Applicable patterns

> Encouraged: name the design / programming / testing patterns this codebase applies
> (e.g. Page Object, Arrange-Act-Assert, Builder for test data) so agents follow them.

{{CONVENTIONS_PATTERNS}}
`,
  },
  {
    name: "grounding",
    title: "Grounding & anti-hallucination",
    body: `# Grounding & anti-hallucination

> Phase 1 seeded this standard. Phase 2 records this project's ground-truth sources in the \`{{PLACEHOLDER}}\` section.

Every claim an agent makes about this system — a path, an API, a schema, a requirement, a test result — must be grounded in a real, checkable artifact. Inventing a plausible-looking file path, function name, or "passing" result is worse than admitting you don't know: it poisons \`context/\` and sends the next run down a dead end. "What's not in context doesn't exist": if you can't read it or cite it, treat it as unknown.

## Rules
- **Cite the source of every factual claim.** Reference \`file:line\`, a ticket id (e.g. Jira \`PROJ-123\`), or the result-MCP output you read it from. A claim with no citable source is a hypothesis — label it as one.
- **Never invent files, paths, APIs, schemas, or results.** If a path or symbol might exist, open it and confirm before relying on it; don't assert a test passed without reading the run's result artifact.
- **Flag uncertainty explicitly.** Write "I could not find…", "unverified", or "assumption:" rather than filling the gap with a confident guess. Surfacing a gap is a finding; hiding it is a defect.
- **Prefer reading over recalling.** Pull the artifact in (source, ticket, trace, JUnit XML via the result MCP) instead of relying on memory or training priors — especially for versions, paths, and API shapes that drift.
- This reinforces, never weakens, the iron QA rule: a "passing" test you did not actually observe pass is not evidence.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — claims carry citations, and the gap is named instead of guessed:
\`\`\`
Empty-password login is rejected by validateCredentials (src/auth/login.ts:42),
tracing to AC PROJ-217. Its e2e test passed this run — read via the
playwright-results MCP (test-results/auth-login). I could not find any test for
the lockout-after-5-tries path; flagging it as uncovered, not assuming covered.
\`\`\`

❌ **Avoid** — confident, uncited, invented; no artifact was opened:
\`\`\`
Login is handled in src/auth/AuthService.login() and all auth tests pass.
\`\`\`

## Applicable patterns

> Encouraged: name the grounding practices this project relies on (cite-by-\`file:line\`,
> result-MCP as the only source of run truth, ticket-id traceability) so agents follow them.

{{GROUNDING_PATTERNS}}

## Project-specific ground-truth sources

> Record where this project's ground truth lives (the schema/SDK of record, the ticket system, the canonical result dirs) so agents read it instead of guessing.

{{PROJECT_GROUNDING_SOURCES}}
`,
  },
  {
    name: "test-naming",
    title: "Test naming",
    body: `# Test naming

> Phase 1 seeded this for **{{PROJECT_LANGUAGE}}** / **{{AUTOMATION_FRAMEWORK}}**.
> Phase 2 refines the \`{{PLACEHOLDER}}\` sections.

## Conventions

- Test names state the behavior and expected outcome, e.g. \`returns 429 when rate limit exceeded\`.
- Case ids are stable and traceable to an acceptance criterion (e.g. \`AC-3.1\`).
- Files/specs mirror the feature under test, one feature area per file.

{{NAMING_RULES}}

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — states behavior + outcome, traceable to an AC:
- \`returns 429 when rate limit exceeded\` → AC-3.1
- \`rejects checkout when the cart is empty\` → AC-7.2

❌ **Avoid** — vague, numbered, or implementation-mirroring names:
- \`test1\`, \`testLogin\`, \`it("works")\`
- \`calls validateCart() then setStatus()\` (mirrors the code, not the behavior)

## Examples from this codebase

> Add a few real names from this codebase so agents copy the right pattern.

{{NAMING_EXAMPLES}}

## Applicable patterns

> Encouraged: naming patterns this codebase uses (e.g. Given-When-Then, "should…",
> one-feature-area-per-file) so agents copy the right shape.

{{NAMING_PATTERNS}}
`,
  },
  {
    name: "diagram-conventions",
    title: "Diagram conventions (Mermaid)",
    body: `# Diagram conventions (Mermaid)

> Phase 1 seeded this standard. Phase 2 adds the project-specific diagrams in the \`{{PLACEHOLDER}}\` section.

Diagrams in \`context/\` and in reports use **Mermaid** fenced code blocks, so they render in the tool and on the repo host, diff cleanly in version control, and never go stale as a binary image. Do not paste screenshots for an architecture or flow that could be Mermaid.

## Which diagram for what
- **\`flowchart\`** — process / decision flow (a test run, the daily loop, a triage path).
- **\`sequenceDiagram\`** — interactions over time (a request across services, an auth handshake); ideal for \`qa-rca\` reproductions and integration-test design.
- **\`stateDiagram-v2\`** — the lifecycle of an entity under test (order, session, work-item).
- **\`erDiagram\`** — data shapes when test data must match a schema (pairs with \`qa-test-data-gen\`).
- **C4 (\`C4Context\`/\`C4Container\`/\`C4Component\`)** — system architecture in \`context/reference/\` (produced by \`qa-reverse-engineer\`); see the C4 mapping below.

## Architecture diagrams — the C4 model
Architecture docs in \`context/reference/\` use the **C4 model**: four levels of zoom, each its own
diagram, so a reader picks the altitude the testing question needs. Map each level to a diagram type:

| C4 level | Scope | Mermaid diagram |
|---|---|---|
| **L1 — System Context** | the system as one box + its users and the external systems it talks to | \`C4Context\` (portable fallback: \`flowchart\`) |
| **L2 — Container** | the deployable/runnable units inside the system boundary (apps, services, data stores, queues) | \`C4Container\` (fallback: \`flowchart\`) |
| **L3 — Component** | the components inside one (testing-critical) container + their entry points | \`C4Component\` (fallback: \`flowchart\`) |
| **L4 — Code** | classes/functions inside a component — usually skipped; generate on demand | \`classDiagram\` (a few key types only) |

- Zoom in only as far as the testing question needs — most QA work lives at **L1–L3**.
- Mermaid's \`C4*\` blocks are the native fit; if a renderer lacks C4 support, fall back to a labeled \`flowchart\` with the same boxes/edges.
- **Don't hand-maintain L4** — it drifts from the code. Link to the source instead (per the \`grounding\` rule).

\`\`\`mermaid
C4Context
  title System context — checkout
  Person(customer, "Customer", "Buys items")
  System(shop, "Shop", "Sells items online")
  System_Ext(psp, "Payment provider", "Charges cards")
  Rel(customer, shop, "Browses & buys")
  Rel(shop, psp, "Authorizes payment")
\`\`\`

## Rules
- Fence as \`\`\`mermaid; one diagram per block; declare direction (\`TD\`/\`LR\`) explicitly.
- Label every node and edge meaningfully. Keep a diagram to ~15 nodes — split a bigger one by domain rather than letting it sprawl.
- The diagram **supports** the prose and traceability; it never replaces the rule that every case traces to an acceptance criterion.
- Reference real source paths in the surrounding text; don't encode detail in the diagram that will drift from the code.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — a fenced, directed, meaningfully labeled Mermaid flowchart:
\`\`\`mermaid
flowchart LR
  A[Acceptance criterion] --> B[Test case]
  B --> C[Automated test]
  C -->|fail| D[qa-rca]
  C -->|pass| E[qa-review]
\`\`\`

❌ **Avoid** — a pasted PNG screenshot (binary, rots, can't diff), or one
unlabeled 40-node blob with no declared direction. Don't paste an image for a
flow that could be Mermaid; split a sprawling diagram by domain instead.

## Applicable patterns

> Encouraged: diagram patterns this product favors (e.g. C4 levels for architecture,
> swimlanes for cross-team flows) so agents reach for the right shape.

{{DIAGRAM_PATTERNS}}

## Project-specific diagrams

> Add the canonical diagrams for this product (key user journeys, the system-context view) once known.

{{PROJECT_DIAGRAMS}}
`,
  },
  {
    name: "documentation-as-code",
    title: "Documentation as code",
    body: `# Documentation as code

> Phase 1 seeded this standard. Phase 2 records the project-specific doc workflow in the \`{{PLACEHOLDER}}\` section.

QA knowledge is treated like source code, not like a wiki. Everything under \`context/\` and the guideline docs lives **in the repo**, is **versioned** with the code it describes, is **reviewed in the same pull request** as the change it documents, is **validated deterministically** by \`doctor\` (structure, links, placeholders, the iron QA rule, the mandatory good/bad examples), and is **kept in sync via CI** — the same pipeline \`qa-ci-pipeline\` builds runs \`doctor\` so docs can't silently rot. "What's not in context doesn't exist": if it isn't written down here, the agent can't use it.

## Rules
- A behavior change and its docs land in **one PR**. Updating \`context/changes/<id>/\` or a guideline is part of the change, not a follow-up.
- Docs link out to real source paths and \`context/foundation/*\`; they never duplicate code or restate general testing advice. Link, don't copy.
- \`doctor\` is the gate, not a human eyeball: broken relative links, leftover phase-1 placeholders, a missing iron QA rule, or a guideline without good/bad examples are **errors** that fail the build.
- Plans are first-class artifacts: active work in \`context/changes/<id>/\`, completed work in \`context/archive/<id>/\` (read-only history). Don't delete history — supersede it.
- Run \`doctor\` in CI (wired by \`qa-ci-pipeline\`) so documentation drift fails the pipeline the same way a failing test does.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the doc changes ride with the code in the same reviewed, CI-checked PR:
\`\`\`
PR #142  "feat: rate-limit checkout (AC-3.1)"
  src/checkout/limiter.ts          (code)
  tests/checkout/limit.spec.ts     (test)
  context/changes/checkout-rate-limit/cases.md   (doc, traces AC-3.1)
  CI: doctor ✅  tests ✅  -> merge
\`\`\`

❌ **Avoid** — knowledge that lives outside the repo, or docs merged without validation:
\`\`\`
"the rate-limit details are in the Confluence page / a Slack thread"
context/foundation/tools.md links to ./does-not-exist.html   # broken link, no CI gate
\`\`\`

## Applicable patterns

> Encouraged: the doc-as-code practices this project applies (docs-in-PR, ADRs, \`doctor\` in CI,
> generated-from-source reference docs) so agents follow the same workflow.

{{DOCS_AS_CODE_PATTERNS}}

## Project-specific doc workflow

> Record this project's concrete workflow once known: where docs are reviewed, which CI job runs \`doctor\`, any doc owners.

{{PROJECT_DOC_WORKFLOW}}
`,
  },
  {
    name: "spec-driven-development",
    title: "Spec-driven development",
    body: `# Spec-driven development

> Phase 1 seeded this standard. Phase 2 records this project's spec workflow in the \`{{PLACEHOLDER}}\` section.

A documented spec — acceptance criteria, expected behavior, edge conditions — comes **before** case design, automation, and code. This is the iron QA rule read from the authoring direction: the iron rule says every test traces *back* to an acceptance criterion; spec-driven development says that criterion must exist and be agreed *first*, so there is something to trace to. No spec ⇒ no cases ⇒ no automation. A test written before its criterion is recorded has nothing to anchor it — it ends up mirroring the implementation instead of the intended behavior.

## Rules
- **Spec precedes design.** Capture the acceptance criteria in \`context/changes/<id>/work.md\` (via \`qa-new\` / \`qa-ticket-review\`) before deriving cases. If the criteria are ambiguous or missing, that is a blocker to resolve — surface it, don't guess your way past it.
- **Cases derive from the spec, not the code.** Every case in \`cases.md\` names the criterion it covers. A case tracing to no criterion is either an undocumented requirement (write the spec) or scope creep (drop it).
- **Each criterion is testable when written.** "Works correctly" is not a criterion; "returns 429 when the rate limit is exceeded" is. \`qa-ticket-review\` marks each criterion testable / not-yet-testable; sharpen the not-yet-testable ones before design starts.
- **Spec changes ripple forward, in order:** update \`work.md\` first, then cases, then automation. Never patch a test to match new behavior while the criterion still describes the old behavior.
- This composes with \`grounding\` (cite the spec text a criterion derives from) and reinforces, never weakens, the iron QA rule.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the criterion is written and agreed first, then the case traces to it:
\`\`\`
work.md   AC-3.1 "API returns 429 once a client exceeds 100 requests/min"
cases.md  TC-12  "returns 429 when rate limit exceeded"  -> traces AC-3.1
test      limit.spec.ts implements TC-12
\`\`\`

❌ **Avoid** — a test written first, with the "spec" reverse-engineered from the code afterwards:
\`\`\`
test      "rate limit works"  (asserts whatever limiter.ts currently does)
work.md   (no acceptance criterion) -> nothing to trace to; mirrors the implementation
\`\`\`

## Applicable patterns

> Encouraged: the spec-first practices this project applies (Specification by Example,
> Given-When-Then acceptance criteria, BDD \`.feature\` files, ticket-as-spec) so agents follow the flow.

{{SPEC_DRIVEN_PATTERNS}}

## Project-specific spec workflow

> Record where this project's specs live and how they are agreed (ticket system, Confluence space, \`.feature\` files, the definition-of-ready) so agents read the spec before designing.

{{PROJECT_SPEC_WORKFLOW}}
`,
  },
  {
    name: "environment-management",
    title: "Environment & secrets management",
    body: `# Environment & secrets management

> Phase 1 seeded this standard. Phase 2 records this project's concrete environment matrix in the \`{{PLACEHOLDER}}\` section.

Tests run against more than one environment — a developer's local stack, CI, a shared staging deployment — and each needs its own base URL, test accounts, and data seeds. The configuration that points a run at an environment must live in **environment variables**, never as a secret committed to the repo. This is the same \`\${VAR}\` / \`\${env:VAR}\` indirection the \`atlassian\` and Playwright browser MCP servers already use for their credentials: the repo declares *which* variables a run needs; the values come from the environment (a local \`.env\` that is git-ignored, the CI secret store, a vault). "What's not in context doesn't exist" cuts both ways — a secret that *is* in context (committed) is a leak.

## Rules
- **Never commit a secret.** No passwords, API tokens, connection strings, or test-account credentials in the repo — not in code, not in config, not in \`context/\`. Reference them by env-var name (\`\${BASE_URL}\`, \`\${env:JIRA_API_TOKEN}\`) and keep the real value in a git-ignored \`.env\`, the CI secret store, or a vault. This is the same indirection the \`atlassian\` / browser MCP wiring uses.
- **One environment matrix, recorded once.** Maintain the local / CI / staging matrix in \`context/foundation/environments.md\`: per environment, its base URL(s), how to obtain a test account, and which data seed it expects. A run names its target environment; it does not hard-code the target's URL.
- **Base URL is configuration, not a literal.** Tests read the base URL from the environment (\`\${BASE_URL}\`), so the same suite runs anywhere. A URL pinned in a spec only works on the author's machine.
- **Test accounts and data seeds are per-environment and disposable.** Each environment has its own accounts and seed; never reuse a production account, and never assume staging data survives between runs. Record where each environment's seed comes from in \`environments.md\`.
- **CI is just another environment in the matrix.** Its variables come from the pipeline's secret store (wired by \`qa-ci-pipeline\`); the repo declares the names, the pipeline supplies the values.

## Examples (✅ good / ❌ bad — required)

> Every guideline shows the pattern, it doesn't just describe it.

✅ **Good** — the target is selected by environment, secrets come from the environment, nothing is committed:
\`\`\`
# .env (git-ignored) — values never committed
BASE_URL=https://staging.shop.example
TEST_USER=qa-bot@example.com
TEST_PASSWORD=…            # from the vault / CI secret store

# test reads configuration, not a literal
await page.goto(process.env.BASE_URL + "/checkout");   // runs on local, CI, staging
\`\`\`

❌ **Avoid** — environment pinned to one machine, a real secret committed to the repo:
\`\`\`
await page.goto("https://staging.shop.example/checkout");  // only works here
const token = "ghp_aJ9…live-token";                        // leaked secret in git history
\`\`\`

## Applicable patterns

> Encouraged: the environment patterns this project applies (\`.env\` + git-ignore, twelve-factor config,
> CI secret store, per-environment base-URL indirection, ephemeral/seeded test data) so agents follow them.

{{ENV_MGMT_PATTERNS}}

## Project-specific environment workflow

> Record this project's concrete matrix once known: each environment's base URL, how to get a test account, where its data seed comes from, and which secret store backs the env vars.

{{PROJECT_ENV_WORKFLOW}}
`,
  },
];

/** The `context/` system of record laid down at scaffold time. */
export const FOUNDATION: Array<{ rel: string; body: string }> = [
  {
    rel: "context/foundation/test-strategy.md",
    body: `# Test strategy

> Durable. Filled by \`qa-init\` in phase 2. Keep lean; link out, don't duplicate.

- **Product under test:** {{PRODUCT_UNDER_TEST}}
- **Critical user journeys:** {{CRITICAL_JOURNEYS}}
- **Risk priorities:** {{RISK_PRIORITIES}}
- **Out of scope:** {{OUT_OF_SCOPE}}
`,
  },
  {
    rel: "context/foundation/test-plan.md",
    body: `# Test plan

> Durable. Owned by the \`test-plan\` skill.

- **Scope:** {{TEST_PLAN_SCOPE}}
- **Test levels & split:** {{TEST_LEVELS}}
- **Entry / exit criteria:** {{ENTRY_EXIT_CRITERIA}}
- **Tooling:** {{AUTOMATION_FRAMEWORK}}
- **Reporting cadence:** {{REPORTING_CADENCE}}
`,
  },
  {
    rel: "context/foundation/environments.md",
    body: `# Environments

> Durable. How to reach each test environment. "What's not in context doesn't exist."

- **Environments:** {{ENVIRONMENTS}}
- **Base URLs / endpoints:** {{BASE_URLS}}
- **Auth / credentials handling:** {{AUTH_HANDLING}}
- **Test data sources:** {{TEST_DATA_SOURCES}}
`,
  },
  {
    rel: "context/foundation/tools.md",
    body: `# Tools & result artifacts

> Durable. Records where test results live so skills can read outcomes directly.

- **Automation framework:** {{AUTOMATION_FRAMEWORK}}
- **Run command:** {{RUN_COMMAND}}
- **Report path:** {{REPORT_PATH}}
- **Trace / screenshot path:** {{TRACE_PATH}}
- **Machine-readable results (e.g. JUnit XML):** {{RESULTS_PATH}}
`,
  },
  {
    rel: "context/foundation/lessons.md",
    body: `# Lessons & golden rules

> Append-only playbook. \`qa-archive\` adds reusable lessons here so future runs
> don't repeat mistakes (flaky areas, data tricks, tooling gotchas).

{{LESSONS}}
`,
  },
  {
    rel: "context/foundation/tech-debt-tracker.md",
    body: `# Tech-debt tracker

> Durable, append-only — a first-class, versioned backlog of test debt and
> known-flaky areas. \`qa-archive\` appends entries as work-items close. Nothing
> here is auto-deleted: an item is resolved by linking the work-item that paid it
> down, not by removing the row, so the history of what we owed survives.

## Open test debt

> Each entry: id, area, what's owed, severity, and the work-item that found/introduced it.

{{TECH_DEBT}}

## Known flaky areas

> Tests or areas that fail intermittently — the quarantine reason and a link to the tracking work-item.

{{FLAKY_AREAS}}
`,
  },
  {
    rel: "context/reference/system-overview.md",
    body: `# System reference — C4 index

> Durable. Produced by \`qa-reverse-engineer\` in phase 2 from the application source, following the
> **C4 model** (L1 Context → L2 Container → L3 Component → L4 Code) rendered with Mermaid — see the
> \`diagram-conventions\` guideline. For a large/monolith codebase the skill first proposes how to split
> this, then fills it. Links out to real source paths — it does not duplicate code.

## Architecture (C4)
- **L1 — System context:** [c4-context.md](./c4-context.md)
- **L2 — Containers:** [c4-container.md](./c4-container.md)
- **L3 — Components:** [c4-component.md](./c4-component.md)
- *L4 — Code:* generated on demand for a specific component; not kept as a standing doc (link to source).

## Business context
> What the system is for, who uses it, and the value it delivers.

{{BUSINESS_CONTEXT}}

## Test surface
> The QA lens over the architecture: what is risky, what is untested, and where the integration seams are.

{{TEST_SURFACE}}
`,
  },
  {
    rel: "context/reference/c4-context.md",
    body: `# C4 L1 — System context

> Durable. Filled by \`qa-reverse-engineer\` (phase 2). One \`C4Context\` (or \`flowchart\` fallback) Mermaid
> diagram per the \`diagram-conventions\` guideline: the system as one box, its users, and the external
> systems it talks to. Confirm every integration in the source before drawing it (\`grounding\`).

{{C4_CONTEXT_DIAGRAM}}

## Users & external systems
> Each actor / external system, what it exchanges with the system, and the integration point in the code.

{{C4_CONTEXT_NOTES}}
`,
  },
  {
    rel: "context/reference/c4-container.md",
    body: `# C4 L2 — Containers

> Durable. Filled by \`qa-reverse-engineer\` (phase 2). A \`C4Container\` (fallback: \`flowchart\`) diagram of
> the deployable/runnable units inside the system boundary (apps, services, data stores, queues) and how
> they communicate. Link each container to its source root.

{{C4_CONTAINER_DIAGRAM}}

## Containers & data flow
> Each container: responsibility, technology, source root, and the data that flows in and out.

{{C4_CONTAINER_NOTES}}
`,
  },
  {
    rel: "context/reference/c4-component.md",
    body: `# C4 L3 — Components

> Durable. Filled by \`qa-reverse-engineer\` (phase 2), zooming into the testing-critical container(s). A
> \`C4Component\` (fallback: \`flowchart\`) diagram of the components inside a container plus the entry
> points (HTTP routes, CLI, jobs, consumers) that exercise them. Skip L4 (code) unless a component needs it.

{{C4_COMPONENT_DIAGRAM}}

## Components & entry points
> Each component: responsibility, key source paths, and the entry point(s) that reach it.

{{C4_COMPONENT_NOTES}}
`,
  },
  {
    rel: "context/changes/.gitkeep",
    body: "",
  },
  {
    rel: "context/archive/.gitkeep",
    body: "",
  },
];
