/**
 * R-104 — the **cost & value dashboard generator**. Emits a single, self-contained
 * `index.html` (inline CSS + hand-rolled SVG + CSS animations, **no external
 * assets** — the zero-dep ethos) that reads its sibling `context/telemetry/index.json`
 * (the aggregate produced by the capture script, R-101, and `qa-cost`, R-105) and
 * renders the client-facing cockpit:
 *
 *  - **totals** (cost, tokens, sessions) with an SVG donut of the real-vs-estimate
 *    split — the load-bearing honesty flag, never hidden;
 *  - **cost per skill/agent** (+ task description) as animated ranked bars;
 *  - **cost ↔ value (ROI)** — cost grouped by the work-item it produced (via the
 *    `workId` trace correlation);
 *  - **by platform** and **by user** (license-utilization, aggregated — not a
 *    ranking of people).
 *
 * The HTML is **static and deterministic** (no dates, no data baked in — the JSON
 * is the only moving part), so the committed `docs/cost-dashboard.html` is
 * snapshot-verified (`tests/cost-dashboard.test.ts`, regenerated by `npm run docs`)
 * and can't drift, exactly like the `skill-flows` / `guideline-flows` generators.
 * The identical string is scaffolded into every repo as
 * `context/telemetry/dashboard.html`.
 *
 * The embedded client script deliberately uses string concatenation (no JS
 * template literals / backticks), so the whole document survives being carried in
 * a `String.raw` template and rendered through the scaffold's placeholder pass
 * untouched (it contains no `{{PLACEHOLDER}}` markers).
 */

export function renderCostDashboard(): string {
  return DASHBOARD_HTML;
}

const DASHBOARD_HTML = String.raw`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>AI cost &amp; value cockpit</title>
<style>
  :root {
    --bg: #0f1420; --panel: #171d2b; --line: #26304a; --ink: #e7ecf5;
    --muted: #93a0bd; --accent: #5b8def; --real: #38c172; --estimate: #f0a742;
    --bar: #5b8def; --bar2: #8f6fe0;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; background: var(--bg); color: var(--ink);
    font: 14px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
  }
  header { padding: 28px 32px 8px; }
  h1 { margin: 0; font-size: 22px; letter-spacing: .2px; }
  .sub { color: var(--muted); margin-top: 4px; font-size: 13px; }
  main { padding: 16px 32px 48px; max-width: 1100px; margin: 0 auto; }
  section { margin-top: 28px; }
  h2 { font-size: 15px; text-transform: uppercase; letter-spacing: .08em; color: var(--muted); margin: 0 0 12px; }
  .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 14px; }
  .card { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; padding: 16px 18px; }
  .card .k { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: .06em; }
  .card .v { font-size: 26px; font-weight: 650; margin-top: 6px; }
  .split { display: flex; gap: 20px; align-items: center; }
  .legend span { display: inline-flex; align-items: center; gap: 6px; margin-right: 14px; font-size: 12px; color: var(--muted); }
  .dot { width: 10px; height: 10px; border-radius: 50%; display: inline-block; }
  .dot.real { background: var(--real); } .dot.estimate { background: var(--estimate); }
  table { width: 100%; border-collapse: collapse; }
  .rows { background: var(--panel); border: 1px solid var(--line); border-radius: 12px; overflow: hidden; }
  .row { display: grid; grid-template-columns: 1fr auto; gap: 8px 16px; padding: 12px 16px; border-top: 1px solid var(--line); }
  .row:first-child { border-top: 0; }
  .row .name { font-weight: 600; }
  .row .desc { color: var(--muted); font-size: 12px; grid-column: 1 / 2; }
  .row .cost { text-align: right; font-variant-numeric: tabular-nums; font-weight: 650; }
  .row .meta { text-align: right; color: var(--muted); font-size: 12px; grid-column: 2 / 3; }
  .track { grid-column: 1 / 3; height: 8px; background: #10182a; border-radius: 6px; overflow: hidden; }
  .fill { height: 100%; width: 0; border-radius: 6px; background: linear-gradient(90deg, var(--bar), var(--bar2));
           animation: grow 900ms cubic-bezier(.2,.7,.2,1) forwards; }
  @keyframes grow { from { width: 0; } }
  .tag { font-size: 11px; padding: 1px 7px; border-radius: 999px; border: 1px solid var(--line); color: var(--muted); }
  .tag.real { color: var(--real); border-color: #1f5c3a; }
  .tag.estimate { color: var(--estimate); border-color: #6b4d1c; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
  .empty { background: var(--panel); border: 1px dashed var(--line); border-radius: 12px; padding: 28px; color: var(--muted); text-align: center; }
  code { background: #0c1220; padding: 2px 6px; border-radius: 5px; }
  .foot { color: var(--muted); font-size: 12px; margin-top: 30px; }
  @media (max-width: 720px) { .grid2 { grid-template-columns: 1fr; } main { padding: 12px 16px 40px; } header { padding: 20px 16px 4px; } }
</style>
</head>
<body>
<header>
  <h1>AI cost &amp; value cockpit</h1>
  <div class="sub">Cost of AI-assisted QA work, per skill and per work-item &mdash; and how much of it is billed vs estimated. License utilization, not a ranking of people.</div>
</header>
<main id="app"><div class="empty">Loading &hellip;</div></main>
<script>
(function () {
  var app = document.getElementById("app");
  fetch("./index.json", { cache: "no-store" })
    .then(function (r) { if (!r.ok) throw new Error("HTTP " + r.status); return r.json(); })
    .then(render)
    .catch(function (e) {
      app.innerHTML =
        '<div class="empty">Could not load <code>index.json</code> (' + esc(String(e)) + ').<br/>' +
        'Serve this folder over a local web server &mdash; e.g. <code>npx serve context/telemetry</code> &mdash; then reload. ' +
        'Run <code>node context/telemetry/capture.mjs</code> first if there is no data yet.</div>';
    });

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return c === "&" ? "&amp;" : c === "<" ? "&lt;" : c === ">" ? "&gt;" : "&quot;";
    });
  }
  function usd(n) { return "$" + (Math.round((n || 0) * 100) / 100).toFixed(2); }
  function intf(n) { return (n || 0).toLocaleString("en-US"); }
  function pctOf(a, b) { return b > 0 ? Math.round((a / b) * 1000) / 10 : 0; }
  function srcTag(g) {
    if (g.real > 0 && g.estimate === 0) return '<span class="tag real">real</span>';
    if (g.estimate > 0 && g.real === 0) return '<span class="tag estimate">estimate</span>';
    if (g.real > 0 && g.estimate > 0) return '<span class="tag">' + g.real + " real / " + g.estimate + " est</span>";
    return "";
  }

  function donut(real, estimate) {
    var total = real + estimate;
    var C = 2 * Math.PI * 52;
    var realLen = total > 0 ? (real / total) * C : 0;
    var svg =
      '<svg width="132" height="132" viewBox="0 0 132 132" role="img" aria-label="real vs estimate">' +
      '<circle cx="66" cy="66" r="52" fill="none" stroke="#f0a742" stroke-width="16"/>' +
      '<circle cx="66" cy="66" r="52" fill="none" stroke="#38c172" stroke-width="16"' +
      ' stroke-dasharray="' + realLen.toFixed(2) + " " + (C - realLen).toFixed(2) + '"' +
      ' transform="rotate(-90 66 66)" stroke-linecap="butt">' +
      '<animate attributeName="stroke-dasharray" from="0 ' + C.toFixed(2) + '" to="' +
      realLen.toFixed(2) + " " + (C - realLen).toFixed(2) + '" dur="0.9s" fill="freeze"/>' +
      "</circle>" +
      '<text x="66" y="62" text-anchor="middle" fill="#e7ecf5" font-size="20" font-weight="700">' +
      pctOf(real, total) + "%</text>" +
      '<text x="66" y="82" text-anchor="middle" fill="#93a0bd" font-size="11">real</text>' +
      "</svg>";
    return svg;
  }

  function barRows(groups, showDesc) {
    if (!groups || groups.length === 0) return '<div class="empty">No data captured yet.</div>';
    var max = groups.reduce(function (m, g) { return Math.max(m, g.costUsd); }, 0) || 1;
    var html = '<div class="rows">';
    for (var i = 0; i < groups.length; i++) {
      var g = groups[i];
      var w = Math.max(2, Math.round((g.costUsd / max) * 100));
      html +=
        '<div class="row">' +
        '<div class="name">' + esc(g.key) + " " + srcTag(g) + "</div>" +
        '<div class="cost">' + usd(g.costUsd) + "</div>" +
        (showDesc && g.description ? '<div class="desc">' + esc(g.description) + "</div>" : '<div class="desc"></div>') +
        '<div class="meta">' + intf(g.tokens) + " tokens &middot; " + intf(g.records) + " sess</div>" +
        '<div class="track"><div class="fill" style="width:' + w + '%"></div></div>' +
        "</div>";
    }
    html += "</div>";
    return html;
  }

  function render(idx) {
    if (!idx || idx.schemaVersion !== 1) {
      app.innerHTML = '<div class="empty">Unrecognized telemetry aggregate.</div>';
      return;
    }
    var t = idx.totals || { records: 0, costUsd: 0, tokens: 0, real: 0, estimate: 0 };
    var out = "";

    out += '<section><div class="cards">';
    out += '<div class="card"><div class="k">Total cost</div><div class="v">' + usd(t.costUsd) + "</div></div>";
    out += '<div class="card"><div class="k">Sessions</div><div class="v">' + intf(t.records) + "</div></div>";
    out += '<div class="card"><div class="k">Tokens</div><div class="v">' + intf(t.tokens) + "</div></div>";
    out +=
      '<div class="card"><div class="k">Real vs estimate</div>' +
      '<div class="split">' + donut(t.real, t.estimate) +
      '<div class="legend"><span><i class="dot real"></i>' + intf(t.real) + " billed/observed</span><br/>" +
      '<span><i class="dot estimate"></i>' + intf(t.estimate) + " estimated</span></div></div></div>";
    out += "</div></section>";

    out += '<section><h2>Cost per skill / agent</h2>' + barRows(idx.bySkill, true) + "</section>";
    out += '<section><h2>Cost &harr; value (per work-item)</h2>' + barRows(idx.byWorkId, false) + "</section>";

    out += '<section class="grid2">';
    out += "<div><h2>By platform</h2>" + barRows(idx.byPlatform, false) + "</div>";
    out += "<div><h2>By user (license utilization)</h2>" + barRows(idx.byUser, false) + "</div>";
    out += "</section>";

    out +=
      '<div class="foot">Every figure is tagged <span class="tag real">real</span> (billed/observed &mdash; Claude local usage) ' +
      'or <span class="tag estimate">estimate</span> (tokenizer estimate &mdash; the sole Copilot source). ' +
      "The two methodologies are shown distinctly and never merged. Generated from <code>index.json</code>; " +
      "aggregated by skill and work-item, not a ranking of people.</div>";

    app.innerHTML = out;
  }
})();
</script>
</body>
</html>
`;
